package com.telesoftas.aoc;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class OrbitsTest {

    private Orbits orbits = new Orbits();

    private String input = "373)6C9\n" +
            "7Y8)CB5\n" +
            "HQT)MJB\n" +
            "PNS)P67\n" +
            "KC2)B72\n" +
            "FSZ)JLN\n" +
            "XBV)JC2\n" +
            "DFZ)4NT\n" +
            "VGX)9KB\n" +
            "XC8)7LW\n" +
            "1CP)Y2R\n" +
            "CPQ)866\n" +
            "ND4)PQK\n" +
            "R6X)RPV\n" +
            "9T7)2NW\n" +
            "C8T)B5J\n" +
            "SVZ)J7N\n" +
            "ZJC)43B\n" +
            "C9F)QC1\n" +
            "T95)5CD\n" +
            "X3K)Y6S\n" +
            "4KT)47S\n" +
            "7Y3)8FL\n" +
            "PWC)CG4\n" +
            "WXF)7M6\n" +
            "WFP)D52\n" +
            "7MG)LGR\n" +
            "FYC)WFD\n" +
            "G3V)GB6\n" +
            "5CL)T9T\n" +
            "M2Y)JVP\n" +
            "YKJ)SBJ\n" +
            "WHK)SHR\n" +
            "B4V)5Q1\n" +
            "34P)VT8\n" +
            "DRP)WHK\n" +
            "BWX)G7N\n" +
            "5DV)Y1J\n" +
            "DN9)JJT\n" +
            "ZH6)G17\n" +
            "GHB)RJY\n" +
            "CWJ)BNW\n" +
            "3M2)FJ2\n" +
            "FBV)YSP\n" +
            "JWL)4JX\n" +
            "6D4)3NR\n" +
            "Z47)5PP\n" +
            "LRH)MN5\n" +
            "NMR)4KT\n" +
            "5QZ)DD5\n" +
            "TH4)JPV\n" +
            "K69)676\n" +
            "KS7)1WM\n" +
            "ZSQ)NS3\n" +
            "NHD)28G\n" +
            "M8W)SWH\n" +
            "X13)V46\n" +
            "J26)SMX\n" +
            "C72)2RJ\n" +
            "HJS)36H\n" +
            "WN2)BYS\n" +
            "PZR)T1K\n" +
            "YXS)68W\n" +
            "717)7MG\n" +
            "5X3)6QS\n" +
            "8JL)271\n" +
            "Z19)9TQ\n" +
            "6WM)JM6\n" +
            "1M1)XR3\n" +
            "235)8KY\n" +
            "K31)GL5\n" +
            "N21)G8D\n" +
            "G5Q)XQ1\n" +
            "1VZ)PTD\n" +
            "W4C)BVN\n" +
            "8R3)2KB\n" +
            "23X)9KY\n" +
            "9C8)VPR\n" +
            "4NT)HTZ\n" +
            "VPW)373\n" +
            "5WG)3DX\n" +
            "C9P)K31\n" +
            "SBJ)HNW\n" +
            "NYX)F5F\n" +
            "BGM)L96\n" +
            "JNP)ZWD\n" +
            "KYD)K6B\n" +
            "MS3)FFT\n" +
            "5LF)H5Z\n" +
            "D6S)9C8\n" +
            "GSC)9NS\n" +
            "KPJ)QHN\n" +
            "MSR)PBR\n" +
            "84J)H67\n" +
            "7WL)WQ7\n" +
            "G6L)7BD\n" +
            "DWR)7C2\n" +
            "676)HPD\n" +
            "KKS)TMW\n" +
            "1XN)S7Y\n" +
            "4KJ)S4Z\n" +
            "9V3)643\n" +
            "LC7)J12\n" +
            "1KQ)QH4\n" +
            "4RJ)H3S\n" +
            "7DC)VGD\n" +
            "NNZ)2BN\n" +
            "1YB)GZR\n" +
            "NJ3)7R4\n" +
            "2RH)P2C\n" +
            "XQ1)1RS\n" +
            "Q3J)YT1\n" +
            "19F)NY1\n" +
            "7JF)MZ5\n" +
            "H3S)NM6\n" +
            "V46)CD8\n" +
            "YZ3)KVB\n" +
            "QC1)3GP\n" +
            "RGP)FGL\n" +
            "L9C)12F\n" +
            "9VT)HW2\n" +
            "3YC)YFL\n" +
            "DRG)FJL\n" +
            "VW1)BWJ\n" +
            "K48)FPQ\n" +
            "ZXF)FYT\n" +
            "9WW)T8F\n" +
            "HWZ)HVV\n" +
            "3TB)F68\n" +
            "Q5H)7JF\n" +
            "18W)67P\n" +
            "Z94)ZH4\n" +
            "RHK)2RQ\n" +
            "CHR)235\n" +
            "PCV)822\n" +
            "22H)2FC\n" +
            "2KX)J4V\n" +
            "K1C)R3H\n" +
            "PFX)RQH\n" +
            "FMJ)SNM\n" +
            "9LW)GHV\n" +
            "3FL)15J\n" +
            "VH8)T2H\n" +
            "P9F)SCV\n" +
            "XWR)VVK\n" +
            "JNX)4G3\n" +
            "DHF)2HZ\n" +
            "SRD)X77\n" +
            "1ZT)6JP\n" +
            "WHM)FBV\n" +
            "F4P)1V5\n" +
            "TJQ)2YD\n" +
            "FR3)CHR\n" +
            "RBS)218\n" +
            "7WJ)BWV\n" +
            "C1K)5C3\n" +
            "2XD)NYX\n" +
            "XQH)3C6\n" +
            "M8H)YPG\n" +
            "3MV)VSZ\n" +
            "Z9G)752\n" +
            "JFY)XWC\n" +
            "ZTG)JGW\n" +
            "XBV)XNQ\n" +
            "PSM)RV7\n" +
            "9DT)J2Q\n" +
            "MFR)T4N\n" +
            "2YV)NZR\n" +
            "F5Z)F46\n" +
            "996)V7Q\n" +
            "5C3)KCQ\n" +
            "XXZ)6YW\n" +
            "Y3D)GXB\n" +
            "HNL)GSC\n" +
            "QW6)9BR\n" +
            "VWN)FSZ\n" +
            "VGD)MFR\n" +
            "PT9)B4V\n" +
            "FD4)23X\n" +
            "5ZM)D4K\n" +
            "JQF)KMM\n" +
            "NTL)NGR\n" +
            "LKB)18Y\n" +
            "H3M)75J\n" +
            "SSC)NBC\n" +
            "GDC)5BG\n" +
            "YYY)K2S\n" +
            "9J7)261\n" +
            "CZW)C6C\n" +
            "YXX)S1M\n" +
            "Y24)LMP\n" +
            "P8W)MS3\n" +
            "P2C)V81\n" +
            "FRJ)X21\n" +
            "C1F)5QJ\n" +
            "271)GF6\n" +
            "6ZB)LC7\n" +
            "9DM)Y3D\n" +
            "T19)KZ7\n" +
            "NTK)F5Z\n" +
            "6ZR)WXJ\n" +
            "FP1)XGG\n" +
            "RB6)8ZW\n" +
            "CFT)S6T\n" +
            "BQB)SGH\n" +
            "YPG)Z3K\n" +
            "BLF)RFZ\n" +
            "XG3)4HZ\n" +
            "1RS)7LP\n" +
            "Y62)C31\n" +
            "BJH)YYY\n" +
            "V9S)DV3\n" +
            "NZ4)8Q9\n" +
            "1ZH)XMD\n" +
            "F68)GYQ\n" +
            "DVH)QST\n" +
            "5N6)VCN\n" +
            "Y6R)6J6\n" +
            "YD9)SRY\n" +
            "CSJ)1N6\n" +
            "QLK)JST\n" +
            "N5B)CJP\n" +
            "R89)KDZ\n" +
            "Y8Y)GWR\n" +
            "8KY)M8W\n" +
            "551)3V1\n" +
            "MJB)DKR\n" +
            "SLN)KDQ\n" +
            "Q2F)SMR\n" +
            "5PX)6WV\n" +
            "LTT)RSB\n" +
            "6WV)SZL\n" +
            "Z3D)4L8\n" +
            "L96)3BV\n" +
            "XSC)SSC\n" +
            "C6C)F4Z\n" +
            "D98)CJ5\n" +
            "3BV)ZY4\n" +
            "G2W)QQR\n" +
            "7R4)QVN\n" +
            "9KY)M9J\n" +
            "22P)2M3\n" +
            "3DD)NN1\n" +
            "CFS)JCP\n" +
            "7N6)33L\n" +
            "DY2)ZZ4\n" +
            "4XP)KZS\n" +
            "NF2)FSJ\n" +
            "45J)W3Z\n" +
            "9WJ)47Q\n" +
            "J5K)GTR\n" +
            "JJT)D1K\n" +
            "18Y)VF3\n" +
            "JBX)6ZB\n" +
            "SP8)6N7\n" +
            "C19)B68\n" +
            "9V9)TTF\n" +
            "CJM)8ZX\n" +
            "Q25)VGX\n" +
            "X8R)B1Z\n" +
            "ZFX)Z6G\n" +
            "YLZ)J83\n" +
            "8R8)WZF\n" +
            "8HZ)9V3\n" +
            "WM3)WSV\n" +
            "HJS)9D2\n" +
            "9J7)W1W\n" +
            "84J)5M4\n" +
            "HXS)NMS\n" +
            "K2R)SN6\n" +
            "X6W)VZH\n" +
            "CD8)4NK\n" +
            "4RQ)19F\n" +
            "J4F)FQ5\n" +
            "LMT)W9Q\n" +
            "CNM)JZ2\n" +
            "QXX)T4C\n" +
            "M3Y)26B\n" +
            "C9F)Y4D\n" +
            "DX9)VFG\n" +
            "PBR)MY5\n" +
            "9LV)LL6\n" +
            "355)3CD\n" +
            "6CQ)HHR\n" +
            "L67)SN3\n" +
            "5SS)4JD\n" +
            "KPB)RM6\n" +
            "23J)JP9\n" +
            "R2W)VKQ\n" +
            "BMV)FR3\n" +
            "CBT)PW1\n" +
            "5CD)47P\n" +
            "22P)YM7\n" +
            "1WM)5TS\n" +
            "3J8)TBN\n" +
            "2HQ)DZB\n" +
            "47S)BQT\n" +
            "D79)TPD\n" +
            "6BJ)TJX\n" +
            "8WT)ZXF\n" +
            "L4L)8GP\n" +
            "NQW)S8F\n" +
            "GVF)LHW\n" +
            "SM1)23J\n" +
            "SCV)N3X\n" +
            "3NF)9R8\n" +
            "SYP)TCP\n" +
            "K9K)XWJ\n" +
            "2BN)XF2\n" +
            "9SD)C6P\n" +
            "TWT)LMT\n" +
            "5W4)PKK\n" +
            "399)VS9\n" +
            "ZTH)226\n" +
            "G79)24V\n" +
            "M59)G2K\n" +
            "HH4)YMN\n" +
            "X99)Y73\n" +
            "68Q)3YR\n" +
            "FMW)NHD\n" +
            "VT8)Y5F\n" +
            "BWV)GS5\n" +
            "5PM)CBL\n" +
            "V53)R1Q\n" +
            "4KT)D2J\n" +
            "89Y)S72\n" +
            "9GR)1KQ\n" +
            "ZH5)FLH\n" +
            "VVM)22P\n" +
            "9ZD)Z25\n" +
            "KRV)S3R\n" +
            "YMN)JGP\n" +
            "JPV)PNL\n" +
            "SN5)69L\n" +
            "RXN)6B9\n" +
            "J4T)717\n" +
            "JT6)DV1\n" +
            "1XJ)MXH\n" +
            "N5L)KKC\n" +
            "PNL)C6T\n" +
            "6L1)T14\n" +
            "CB5)SBL\n" +
            "49B)TWT\n" +
            "5Q1)91L\n" +
            "5DP)FMN\n" +
            "KL5)K63\n" +
            "6SS)HFN\n" +
            "3W8)ZGG\n" +
            "SPZ)ZRH\n" +
            "W2N)QLG\n" +
            "W9Q)D4X\n" +
            "F23)PLW\n" +
            "ZGG)LTT\n" +
            "6WM)RWY\n" +
            "6MP)WKG\n" +
            "G5H)M8Z\n" +
            "ZZ4)YMG\n" +
            "V81)7SF\n" +
            "7NY)KNJ\n" +
            "SMB)1XN\n" +
            "JM6)744\n" +
            "XMD)C77\n" +
            "LRM)X3Z\n" +
            "Q5G)733\n" +
            "2MK)21P\n" +
            "R1B)DKM\n" +
            "XBW)YJM\n" +
            "XWJ)68B\n" +
            "VZX)L67\n" +
            "SLC)ZJC\n" +
            "CK4)3MV\n" +
            "K59)G79\n" +
            "TT6)L15\n" +
            "8ST)7D7\n" +
            "M5F)PCV\n" +
            "HLZ)44L\n" +
            "92Y)R2W\n" +
            "XR3)K48\n" +
            "Y5F)GFH\n" +
            "RZ2)NJ3\n" +
            "RKG)RXN\n" +
            "8HF)VH8\n" +
            "V8Q)7NH\n" +
            "JH7)PYL\n" +
            "RH2)FWH\n" +
            "NBP)VVM\n" +
            "BP1)8TS\n" +
            "47P)MXY\n" +
            "WFT)R6N\n" +
            "992)VDG\n" +
            "HWB)QG8\n" +
            "CC7)H8R\n" +
            "3JH)MNM\n" +
            "MV5)37P\n" +
            "K58)QMH\n" +
            "H31)5PM\n" +
            "QHN)HG7\n" +
            "LMY)5H9\n" +
            "6CM)C9F\n" +
            "Q9Z)C46\n" +
            "GVF)5N7\n" +
            "78J)DLC\n" +
            "D4Y)NNZ\n" +
            "MQR)6RG\n" +
            "NDG)NHH\n" +
            "Y8H)14B\n" +
            "789)J26\n" +
            "S8S)Q25\n" +
            "JRQ)L4L\n" +
            "TC6)TPH\n" +
            "7Y9)WY3\n" +
            "46N)419\n" +
            "Z6G)KHM\n" +
            "J8D)TJQ\n" +
            "YVK)V49\n" +
            "V49)JMD\n" +
            "HT9)NQT\n" +
            "F65)SPW\n" +
            "6RG)YS3\n" +
            "YPZ)S4C\n" +
            "R6N)VW1\n" +
            "6N7)J8D\n" +
            "4J3)TFK\n" +
            "Q7B)9J7\n" +
            "FYT)HWB\n" +
            "GFT)NTL\n" +
            "ZW7)S8S\n" +
            "QMH)6CQ\n" +
            "W2G)F11\n" +
            "QVN)C8T\n" +
            "L5H)TJJ\n" +
            "PKK)Z6L\n" +
            "MZ5)LPV\n" +
            "QC1)CHF\n" +
            "8GB)LV5\n" +
            "X21)8R8\n" +
            "M7P)2KX\n" +
            "PB2)GR2\n" +
            "TMZ)BCL\n" +
            "GLW)VDC\n" +
            "SGZ)DFH\n" +
            "SH6)KTZ\n" +
            "2ND)6RF\n" +
            "TTD)MBX\n" +
            "C6T)SPZ\n" +
            "S4H)N4T\n" +
            "PB2)BP1\n" +
            "W1W)NTR\n" +
            "B8H)XH7\n" +
            "WKB)XZZ\n" +
            "J1T)MD7\n" +
            "3MQ)DN9\n" +
            "K6B)WQF\n" +
            "HJ7)HJS\n" +
            "1WJ)LM4\n" +
            "FH8)7SV\n" +
            "QVX)XPS\n" +
            "1N6)W9B\n" +
            "NMF)VTJ\n" +
            "1TR)NDF\n" +
            "LM4)ML4\n" +
            "VPR)DHF\n" +
            "Y6J)9YH\n" +
            "LCG)LCV\n" +
            "RQH)T29\n" +
            "KS7)G24\n" +
            "8WK)7W4\n" +
            "MLY)VM8\n" +
            "KMM)KL8\n" +
            "T29)5QB\n" +
            "HTD)NBP\n" +
            "MN5)BXP\n" +
            "S8F)6NJ\n" +
            "2XK)YN4\n" +
            "74L)ZTC\n" +
            "XTY)N5C\n" +
            "W7B)7LS\n" +
            "XWC)1VZ\n" +
            "CNX)L1G\n" +
            "4JX)KCH\n" +
            "7D2)73S\n" +
            "3CD)TKJ\n" +
            "743)F65\n" +
            "CMB)XNG\n" +
            "DJ7)BPJ\n" +
            "4BQ)PNS\n" +
            "419)NZ4\n" +
            "2RJ)DVH\n" +
            "J7N)X9M\n" +
            "PKK)MR1\n" +
            "6JK)B64\n" +
            "ZGJ)DJQ\n" +
            "F11)CNM\n" +
            "SK6)HW5\n" +
            "9MT)5LF\n" +
            "TBN)KYD\n" +
            "5K4)BWT\n" +
            "8FL)V5T\n" +
            "GWR)9ZZ\n" +
            "L1J)KRV\n" +
            "SF8)Z6H\n" +
            "VFQ)TT6\n" +
            "CGT)V37\n" +
            "LV5)K8T\n" +
            "FL3)8XY\n" +
            "RJY)KQM\n" +
            "P3T)1GP\n" +
            "RM6)R6X\n" +
            "Q7M)4JJ\n" +
            "WN7)Y8H\n" +
            "2MJ)YLH\n" +
            "QHR)1MD\n" +
            "LP9)BHH\n" +
            "NL6)J4T\n" +
            "4QW)9VQ\n" +
            "YS3)6P7\n" +
            "VSZ)XG3\n" +
            "P13)JSM\n" +
            "9YH)4KD\n" +
            "N5C)G6Y\n" +
            "Z38)DY3\n" +
            "4WF)LPJ\n" +
            "51Y)H8N\n" +
            "R3H)MGH\n" +
            "KY9)49B\n" +
            "3Z4)N4N\n" +
            "F6L)1G8\n" +
            "1RC)M56\n" +
            "61F)DRG\n" +
            "V7V)9SD\n" +
            "21Z)LMY\n" +
            "L4Z)N5B\n" +
            "D2J)PWT\n" +
            "YT1)S1F\n" +
            "X9M)LJP\n" +
            "LL6)K59\n" +
            "NW7)TH4\n" +
            "RL2)Z3D\n" +
            "M56)L9Q\n" +
            "1MD)C16\n" +
            "PVB)QW6\n" +
            "SNM)MPW\n" +
            "9ZL)XTZ\n" +
            "MBX)CK4\n" +
            "MSL)2XV\n" +
            "K8T)MDC\n" +
            "YMG)XG5\n" +
            "261)XD8\n" +
            "LQS)JQF\n" +
            "WY9)8D4\n" +
            "HTZ)PB2\n" +
            "F5F)1XL\n" +
            "L99)Q6C\n" +
            "NDF)PQF\n" +
            "JC2)W9H\n" +
            "ZB4)F23\n" +
            "JSM)9L8\n" +
            "9NQ)B2Y\n" +
            "VBY)X7W\n" +
            "ZGJ)WFT\n" +
            "ZCP)ZYV\n" +
            "S1F)W73\n" +
            "FG5)M7P\n" +
            "ML3)7GF\n" +
            "891)Y5M\n" +
            "WPL)2FM\n" +
            "1XL)3YC\n" +
            "WQF)VRV\n" +
            "LGR)S9J\n" +
            "TKJ)CWH\n" +
            "HCV)QXX\n" +
            "8XP)NVD\n" +
            "WFD)ML3\n" +
            "7W4)HPH\n" +
            "TT3)VYK\n" +
            "KWS)BZ4\n" +
            "9JW)8ST\n" +
            "DMS)2XT\n" +
            "8G8)PSX\n" +
            "ZH8)3SC\n" +
            "TSH)JKC\n" +
            "DV1)X4Y\n" +
            "VVR)SSK\n" +
            "VGN)J5Z\n" +
            "X4Y)RHK\n" +
            "XNQ)JNP\n" +
            "MWZ)JGH\n" +
            "B64)L5C\n" +
            "7BD)N3S\n" +
            "9NQ)FY6\n" +
            "DFH)SH6\n" +
            "Q4B)G4S\n" +
            "8VR)46G\n" +
            "SK6)PFY\n" +
            "6NJ)VQ8\n" +
            "DL6)MNJ\n" +
            "BWJ)3TB\n" +
            "F46)G3V\n" +
            "Y3S)DK1\n" +
            "NMS)V8Q\n" +
            "XFL)RZ7\n" +
            "DD5)CWJ\n" +
            "K4C)5QZ\n" +
            "DB6)S9H\n" +
            "HDX)GV7\n" +
            "H8R)X99\n" +
            "6Y7)VWN\n" +
            "Y9X)PQ6\n" +
            "QPL)WX4\n" +
            "3WT)5DD\n" +
            "C46)FFZ\n" +
            "QYY)K3G\n" +
            "5YG)4XP\n" +
            "N9H)4QP\n" +
            "J2Q)4YN\n" +
            "SW3)LQS\n" +
            "DBR)D8Z\n" +
            "SWH)SGZ\n" +
            "9YB)C9P\n" +
            "L1H)KP8\n" +
            "DMS)SPX\n" +
            "QK6)SAN\n" +
            "CHF)6BJ\n" +
            "XH7)Z8L\n" +
            "YXY)T9W\n" +
            "COM)FV9\n" +
            "Q4P)DMF\n" +
            "PLW)QD2\n" +
            "NY1)682\n" +
            "F1L)YPD\n" +
            "LV7)5YG\n" +
            "KZ6)Z94\n" +
            "CPF)4M5\n" +
            "V1W)FYC\n" +
            "GHV)HW7\n" +
            "37T)CFS\n" +
            "D2G)CC7\n" +
            "YSP)V8D\n" +
            "KZ7)YLZ\n" +
            "37P)YVK\n" +
            "KDQ)25L\n" +
            "NR6)7WW\n" +
            "4KD)CWX\n" +
            "4QP)BYF\n" +
            "H8N)G5R\n" +
            "NQB)8HZ\n" +
            "PBL)97M\n" +
            "8FZ)GTH\n" +
            "HKG)HCV\n" +
            "X3Z)3BD\n" +
            "91L)Z73\n" +
            "RBW)9LV\n" +
            "NPC)3KQ\n" +
            "NHH)7D2\n" +
            "D79)1LG\n" +
            "3V8)TSH\n" +
            "1V5)7Y3\n" +
            "B5H)Y8Y\n" +
            "3YR)GRV\n" +
            "KHM)VTR\n" +
            "4H9)G8X\n" +
            "28G)J1T\n" +
            "NTR)V59\n" +
            "96W)H4H\n" +
            "BVN)JJ7\n" +
            "XPS)Q8X\n" +
            "NTW)4G4\n" +
            "13C)XDB\n" +
            "D52)DMS\n" +
            "W9H)HCQ\n" +
            "3DX)7DC\n" +
            "3RF)V7P\n" +
            "NTG)RH2\n" +
            "P8R)6CM\n" +
            "NVN)LBQ\n" +
            "68B)RH8\n" +
            "PQ6)PT9\n" +
            "6WV)8G8\n" +
            "733)HQH\n" +
            "RPH)1HG\n" +
            "CWX)XWR\n" +
            "PTD)Z9G\n" +
            "J7Z)9XV\n" +
            "P5J)NTG\n" +
            "6JP)68Q\n" +
            "DJQ)9ZD\n" +
            "Z4W)3W3\n" +
            "VRV)2YV\n" +
            "M3Y)CMB\n" +
            "GTR)K58\n" +
            "R1Q)WSY\n" +
            "ZWD)Q3J\n" +
            "H5Z)B44\n" +
            "LCV)P8W\n" +
            "VW1)ZB4\n" +
            "4G3)YLX\n" +
            "R4M)R99\n" +
            "ZYK)R4M\n" +
            "WNJ)9WJ\n" +
            "7LS)16X\n" +
            "8ZW)GHB\n" +
            "D4X)YG2\n" +
            "VFG)VHX\n" +
            "RFW)XXX\n" +
            "611)6Z2\n" +
            "6YW)QPL\n" +
            "P7B)JHC\n" +
            "L19)NMF\n" +
            "DF9)YQM\n" +
            "QDW)634\n" +
            "25L)SMB\n" +
            "1TL)6DM\n" +
            "9NS)GVF\n" +
            "W8D)2RH\n" +
            "WJK)8GB\n" +
            "KNL)ZHK\n" +
            "M73)1PV\n" +
            "Z3K)Z5G\n" +
            "TDJ)BQ8\n" +
            "XRD)HT5\n" +
            "HY9)RBH\n" +
            "JJ7)6PJ\n" +
            "1QL)G5Q\n" +
            "T66)W4C\n" +
            "YMC)CTM\n" +
            "VY3)88V\n" +
            "LJD)44K\n" +
            "BMP)6Y5\n" +
            "8SD)GTB\n" +
            "5H9)PJF\n" +
            "GY7)4RQ\n" +
            "FF6)HNL\n" +
            "GRV)RFW\n" +
            "YFL)836\n" +
            "3HY)NVN\n" +
            "HW2)CZW\n" +
            "8JL)D79\n" +
            "68B)4Z9\n" +
            "FPQ)Q7B\n" +
            "45T)QYY\n" +
            "KCH)MSR\n" +
            "DL4)W7S\n" +
            "9RK)CSJ\n" +
            "7S2)YXY\n" +
            "4L8)WB7\n" +
            "LJN)M3S\n" +
            "DBR)8TT\n" +
            "YNY)1W3\n" +
            "VZX)HWM\n" +
            "V59)KMG\n" +
            "337)8HB\n" +
            "DKR)749\n" +
            "NZR)FD4\n" +
            "V7P)1RC\n" +
            "SW2)TMZ\n" +
            "MQR)4BQ\n" +
            "BZ4)S6B\n" +
            "LPJ)WHZ\n" +
            "24Z)NQW\n" +
            "CRT)KKS\n" +
            "Q7Z)4QM\n" +
            "L34)S57\n" +
            "FLY)MWZ\n" +
            "DK1)HTX\n" +
            "7YW)L9C\n" +
            "7LW)6WM\n" +
            "PYC)7P7\n" +
            "R3H)891\n" +
            "BXP)N9H\n" +
            "YM7)9TK\n" +
            "4TS)WM3\n" +
            "TXG)HTD\n" +
            "SQ5)Z4T\n" +
            "TFK)HLZ\n" +
            "B61)4SG\n" +
            "9H2)37T\n" +
            "RXZ)WPL\n" +
            "FMN)ZKD\n" +
            "NVD)B55\n" +
            "HG7)673\n" +
            "C95)J5K\n" +
            "JCP)71P\n" +
            "WQ7)99C\n" +
            "VDM)L21\n" +
            "WBB)4BJ\n" +
            "L1B)TTZ\n" +
            "JC2)337\n" +
            "TC3)74L\n" +
            "YN4)25P\n" +
            "97M)KHD\n" +
            "P8D)S4H\n" +
            "Y4D)GMV\n" +
            "WCM)CDF\n" +
            "V5T)RBS\n" +
            "6DH)ZLC\n" +
            "VM8)G4K\n" +
            "GYD)BGM\n" +
            "Y8L)XN1\n" +
            "TWV)GLZ\n" +
            "RV7)P5J\n" +
            "47P)PFX\n" +
            "NS3)H41\n" +
            "1XL)1QL\n" +
            "G6Y)QY9\n" +
            "GYQ)V9S\n" +
            "47Q)C1K\n" +
            "WGC)D1Z\n" +
            "26B)HDH\n" +
            "JQ5)2SW\n" +
            "SS2)NL6\n" +
            "9SP)3W8\n" +
            "H5N)96W\n" +
            "LCN)ZTH\n" +
            "18Y)VNH\n" +
            "WJP)VZQ\n" +
            "B2X)XC8\n" +
            "6VQ)RSZ\n" +
            "L1P)DY2\n" +
            "XN1)2HQ\n" +
            "MV3)GG7\n" +
            "K48)X1R\n" +
            "41F)P3V\n" +
            "RWY)KR8\n" +
            "WBS)T95\n" +
            "BJM)G1Z\n" +
            "T1K)BMV\n" +
            "B2F)LF2\n" +
            "BD6)C1F\n" +
            "2FC)3JH\n" +
            "5QB)46H\n" +
            "FFT)1TR\n" +
            "88V)YD9\n" +
            "JNB)87W\n" +
            "3MD)89Y\n" +
            "43B)RBW\n" +
            "VDM)MLY\n" +
            "WV9)P8D\n" +
            "HJL)SW2\n" +
            "LFN)W2N\n" +
            "3JH)CTW\n" +
            "NVC)MH8\n" +
            "BNW)ZCP\n" +
            "BXH)9LD\n" +
            "V8D)Q2F\n" +
            "1HG)SRD\n" +
            "GB6)LV7\n" +
            "3ND)BPQ\n" +
            "6DT)34P\n" +
            "PQF)MV5\n" +
            "KL8)YC5\n" +
            "D76)8SD\n" +
            "2XV)P5S\n" +
            "GLZ)3M9\n" +
            "5LR)WN7\n" +
            "N4T)PZR\n" +
            "FFT)RB6\n" +
            "9TQ)8P2\n" +
            "68V)5K4\n" +
            "3R9)LCZ\n" +
            "VVK)X5K\n" +
            "D1K)RPP\n" +
            "TPH)996\n" +
            "HTF)BTH\n" +
            "ML4)TC6\n" +
            "BP9)HQC\n" +
            "H41)2XD\n" +
            "H8B)JTV\n" +
            "QVN)P1Z\n" +
            "KTZ)NW6\n" +
            "B42)X8R\n" +
            "8D4)T6P\n" +
            "BPQ)NW7\n" +
            "VVF)NB7\n" +
            "XGG)1HD\n" +
            "5XT)MHK\n" +
            "JST)RLD\n" +
            "5PX)R1B\n" +
            "LKB)PYC\n" +
            "GFH)J7Z\n" +
            "N3S)3ND\n" +
            "XPX)HZX\n" +
            "X79)VPW\n" +
            "3ZJ)SM1\n" +
            "JWM)JQL\n" +
            "M9J)SK6\n" +
            "F9B)PWC\n" +
            "G4Z)LP9\n" +
            "9CG)JBX\n" +
            "M5F)GKV\n" +
            "S9J)43P\n" +
            "6B9)3MD\n" +
            "TMR)7NY\n" +
            "7LP)RTF\n" +
            "JZ2)VHV\n" +
            "GJ9)XFL\n" +
            "TJX)PSM\n" +
            "TQM)Y3S\n" +
            "PJF)G82\n" +
            "8KY)51Y\n" +
            "S3R)Q8H\n" +
            "3Z4)K2R\n" +
            "XTZ)JWM\n" +
            "HS1)BP9\n" +
            "1CP)C3Z\n" +
            "99J)992\n" +
            "P3V)FLY\n" +
            "LNC)W7B\n" +
            "QGH)HKG\n" +
            "R36)KZW\n" +
            "GGJ)XS3\n" +
            "9M5)3J6\n" +
            "M3S)QP4\n" +
            "GLB)JB9\n" +
            "BDQ)PDK\n" +
            "ZH5)99J\n" +
            "TPD)QBL\n" +
            "V7Q)NF5\n" +
            "N3X)LCG\n" +
            "DYJ)M59\n" +
            "8XY)2ND\n" +
            "WTG)J4F\n" +
            "XXZ)3DD\n" +
            "PTS)5DV\n" +
            "WVP)M57\n" +
            "7SV)TC3\n" +
            "71K)3VP\n" +
            "T2H)5W4\n" +
            "P5S)KZC\n" +
            "3M9)9DT\n" +
            "D4K)Q5H\n" +
            "7WJ)7Y9\n" +
            "ZKD)X13\n" +
            "JMD)9DM\n" +
            "3N8)HH4\n" +
            "LDJ)M2Y\n" +
            "D16)BMP\n" +
            "7M6)WMC\n" +
            "5LV)78J\n" +
            "3KQ)VVF\n" +
            "GKV)KDS\n" +
            "7NH)9WW\n" +
            "6ZG)NRC\n" +
            "1LG)NDG\n" +
            "NL3)SW6\n" +
            "DY3)D2G\n" +
            "FWH)9V9\n" +
            "P1Z)1T7\n" +
            "VDG)SZY\n" +
            "46H)TXG\n" +
            "ZBJ)RFQ\n" +
            "ZYV)5VC\n" +
            "44V)N6J\n" +
            "5VC)399\n" +
            "C38)QQ7\n" +
            "2XT)X6W\n" +
            "4MF)WMQ\n" +
            "P3H)P7B\n" +
            "WHZ)P1X\n" +
            "C77)XSC\n" +
            "3GP)FF6\n" +
            "23X)WNR\n" +
            "8TT)JWJ\n" +
            "866)WQL\n" +
            "6S6)WGC\n" +
            "X5K)2NH\n" +
            "XD8)LJD\n" +
            "ZLW)JWV\n" +
            "VPR)5XT\n" +
            "VHX)5WG\n" +
            "TWT)XPX\n" +
            "WBB)6LZ\n" +
            "RR9)K4N\n" +
            "218)DB6\n" +
            "6BX)Z4W\n" +
            "4QT)PD8\n" +
            "6TQ)L4Z\n" +
            "KZW)YXX\n" +
            "2RM)ZSQ\n" +
            "LJP)45K\n" +
            "CK4)1XJ\n" +
            "9SP)9JW\n" +
            "4SG)5DP\n" +
            "VTJ)K6X\n" +
            "W4V)8FZ\n" +
            "DBT)SVZ\n" +
            "6SG)Z1G\n" +
            "LF2)NJS\n" +
            "68V)6Y7\n" +
            "HLQ)LNC\n" +
            "NGR)CS5\n" +
            "PVN)DL6\n" +
            "TT7)3M2\n" +
            "L67)FMW\n" +
            "5N7)7N6\n" +
            "HCG)JFY\n" +
            "QP4)TBW\n" +
            "4M5)F4P\n" +
            "S1M)G2W\n" +
            "HVV)1TL\n" +
            "KDS)FGH\n" +
            "915)41F\n" +
            "1G7)9CG\n" +
            "SW2)K69\n" +
            "KWK)9GF\n" +
            "KSJ)5SS\n" +
            "RLD)WNJ\n" +
            "C7W)HY9\n" +
            "T7W)G6L\n" +
            "FMN)GFT\n" +
            "GGP)X79\n" +
            "MGH)SLC\n" +
            "9NL)5LL\n" +
            "B5J)RGP\n" +
            "DKM)QY5\n" +
            "4BJ)HTF\n" +
            "M9L)FP1\n" +
            "PQK)H3M\n" +
            "58G)551\n" +
            "JFY)Y6R\n" +
            "D24)9M5\n" +
            "142)743\n" +
            "Z8L)HC4\n" +
            "KVB)HD9\n" +
            "P8W)WJK\n" +
            "6RF)6YG\n" +
            "8HB)VTW\n" +
            "B2Y)68V\n" +
            "X6W)DYZ\n" +
            "752)VDM\n" +
            "QNV)PVN\n" +
            "682)B2X\n" +
            "K6T)HT9\n" +
            "DLC)SW3\n" +
            "24V)ZLW\n" +
            "3TV)NL3\n" +
            "HNS)G5H\n" +
            "GT2)JGF\n" +
            "WB7)21Z\n" +
            "SHR)VJM\n" +
            "2CP)F6L\n" +
            "GS5)TQM\n" +
            "VHV)Z47\n" +
            "HWM)WHM\n" +
            "TTF)CM3\n" +
            "9BR)P8R\n" +
            "SGH)WQZ\n" +
            "CTW)6VQ\n" +
            "JRW)3J8\n" +
            "8XY)X3K\n" +
            "LCZ)TT3\n" +
            "DMX)VZX\n" +
            "5DD)2MK\n" +
            "RB4)YJY\n" +
            "XG9)MV3\n" +
            "LBQ)WZD\n" +
            "C6P)WVP\n" +
            "T9W)CMK\n" +
            "ND4)V7V\n" +
            "T8F)YOU\n" +
            "37P)HBQ\n" +
            "43P)9H2\n" +
            "WFP)84P\n" +
            "Y2R)KC2\n" +
            "NXF)GZM\n" +
            "6PJ)9T7\n" +
            "1ZT)DDZ\n" +
            "GVH)DYJ\n" +
            "Z5G)F2P\n" +
            "673)ZBJ\n" +
            "BQ8)HRJ\n" +
            "NRC)CJM\n" +
            "QY9)4KK\n" +
            "HNW)GRR\n" +
            "FGL)Q9Z\n" +
            "B68)7Y8\n" +
            "99C)C72\n" +
            "SN3)JWL\n" +
            "Z6H)WTG\n" +
            "BQT)5X3\n" +
            "KMG)LFN\n" +
            "G8D)DX7\n" +
            "6RF)FTB\n" +
            "5KB)JRQ\n" +
            "ZWD)QZ1\n" +
            "L9Q)SVF\n" +
            "JGW)495\n" +
            "HPH)ZYK\n" +
            "QBL)VK7\n" +
            "1ZR)4WF\n" +
            "5LL)QNV\n" +
            "WX4)LCN\n" +
            "H66)RW5\n" +
            "GTH)RR9\n" +
            "4FL)LY9\n" +
            "G7N)WFP\n" +
            "BJH)4KJ\n" +
            "RH8)DBR\n" +
            "CM3)QZV\n" +
            "WZD)5J2\n" +
            "BVK)TMD\n" +
            "S72)4H9\n" +
            "RSB)3BN\n" +
            "DYZ)51P\n" +
            "8ZX)NVC\n" +
            "JB8)HS1\n" +
            "GGV)NXF\n" +
            "Y73)CLH\n" +
            "3TX)Y8L\n" +
            "3GJ)T7W\n" +
            "2MJ)N21\n" +
            "WXJ)L4T\n" +
            "KZC)VY3\n" +
            "WXR)6S6\n" +
            "DMF)KWK\n" +
            "GWC)915\n" +
            "6TD)KZ6\n" +
            "CJP)PBL\n" +
            "MDC)BWX\n" +
            "86B)Y6J\n" +
            "GV7)74P\n" +
            "5PP)45J\n" +
            "JWJ)GLB\n" +
            "GRR)44G\n" +
            "S9H)PJ5\n" +
            "GHV)M8H\n" +
            "VTW)T19\n" +
            "4L2)6MP\n" +
            "WZF)Y9X\n" +
            "1GP)BCY\n" +
            "CTM)NZ6\n" +
            "VZQ)GVH\n" +
            "36H)NGV\n" +
            "CJ5)1V3\n" +
            "RPV)6FC\n" +
            "X7W)YMC\n" +
            "WHM)NSP\n" +
            "TC3)3RF\n" +
            "X77)WBS\n" +
            "44K)BLF\n" +
            "BTN)PTS\n" +
            "JZ4)V4P\n" +
            "RWB)BVK\n" +
            "B44)GWC\n" +
            "HJG)142\n" +
            "S4Z)CGT\n" +
            "SPX)61F\n" +
            "XZZ)PVB\n" +
            "FK4)9RK\n" +
            "M1Q)R2T\n" +
            "FJ6)F5Q\n" +
            "XM6)B8V\n" +
            "NM6)1ZH\n" +
            "NXX)VBY\n" +
            "7Y3)P3H\n" +
            "9L8)DRB\n" +
            "MVC)QR3\n" +
            "HDH)6ZR\n" +
            "NS3)HLQ\n" +
            "3C6)9MY\n" +
            "SN6)R36\n" +
            "FTB)GGV\n" +
            "VQ6)PQ1\n" +
            "GL5)HDX\n" +
            "14B)8WT\n" +
            "ZP9)Z19\n" +
            "FFZ)45T\n" +
            "84N)5LV\n" +
            "FYT)BXH\n" +
            "CTZ)ND4\n" +
            "CG4)KBZ\n" +
            "HQH)84N\n" +
            "Z1G)W87\n" +
            "VF3)Q3T\n" +
            "J12)D98\n" +
            "BCL)C7W\n" +
            "N3M)5CL\n" +
            "XS3)YZ3\n" +
            "Z47)3Z4\n" +
            "495)3PZ\n" +
            "QST)ZH5\n" +
            "MNY)L1J\n" +
            "9LD)MXX\n" +
            "JGF)RZ2\n" +
            "NZX)LRH\n" +
            "51P)2RM\n" +
            "MXH)C19\n" +
            "MD7)3NF\n" +
            "BXY)5NH\n" +
            "L4T)9VT\n" +
            "NSP)XTY\n" +
            "X5M)K6T\n" +
            "24Z)X5Q\n" +
            "2NH)4QW\n" +
            "JVP)KSJ\n" +
            "S6B)L19\n" +
            "TTD)52H\n" +
            "HPD)628\n" +
            "44G)3HY\n" +
            "YG2)G1T\n" +
            "628)Y62\n" +
            "HCQ)6BX\n" +
            "Q4B)141\n" +
            "8TS)YNY\n" +
            "SMX)KY9\n" +
            "67P)GDC\n" +
            "WY9)QGH\n" +
            "QD2)3WT\n" +
            "X5T)SF8\n" +
            "1T7)FL3\n" +
            "VS9)XXZ\n" +
            "QQR)5LR\n" +
            "VDC)G1V\n" +
            "5QJ)VV7\n" +
            "5BG)1WJ\n" +
            "PFY)H31\n" +
            "52H)27L\n" +
            "G2K)T66\n" +
            "J83)3MQ\n" +
            "PYY)DWR\n" +
            "G4S)HWZ\n" +
            "QZ1)XHL\n" +
            "HHR)6DH\n" +
            "73S)CBT\n" +
            "FJL)B2F\n" +
            "6LZ)92Y\n" +
            "SRR)Z8J\n" +
            "9ZD)SP8\n" +
            "B55)B5H\n" +
            "19F)84J\n" +
            "6J6)YXS\n" +
            "YJY)XRD\n" +
            "KR8)NMR\n" +
            "BSN)C95\n" +
            "VYK)6SS\n" +
            "3J6)YPZ\n" +
            "H67)JQ5\n" +
            "6CM)XBW\n" +
            "TCP)B1P\n" +
            "KZS)HXH\n" +
            "75J)NTW\n" +
            "FGH)XYD\n" +
            "9DG)NQB\n" +
            "HYH)BD6\n" +
            "CBL)8R3\n" +
            "SZY)HQT\n" +
            "V4P)BJM\n" +
            "WQZ)FYR\n" +
            "KWB)RPH\n" +
            "1BX)VGN\n" +
            "KCQ)13C\n" +
            "4NK)XG9\n" +
            "DX7)SLN\n" +
            "P67)9NQ\n" +
            "HTD)LRM\n" +
            "JLN)2N3\n" +
            "FV9)DFZ\n" +
            "FY6)CNX\n" +
            "2KB)KNL\n" +
            "GZM)K9K\n" +
            "XYD)QWT\n" +
            "7P7)LXC\n" +
            "RL2)2RT\n" +
            "7BX)5HY\n" +
            "1W3)BBV\n" +
            "836)TT7\n" +
            "G8X)FMJ\n" +
            "G4K)SYP\n" +
            "16X)1ZT\n" +
            "VJM)CRT\n" +
            "6L1)L5H\n" +
            "Z4T)GT2\n" +
            "2M3)611\n" +
            "WKG)R55\n" +
            "JRW)6D4\n" +
            "ZYP)V53\n" +
            "87W)SQ5\n" +
            "4KD)KS7\n" +
            "HJ7)58G\n" +
            "C46)K1C\n" +
            "Y2D)PYY\n" +
            "373)NTK\n" +
            "DRB)VVR\n" +
            "N4N)6TQ\n" +
            "VH1)24Z\n" +
            "NBC)D29\n" +
            "JGP)M47\n" +
            "YLX)MSL\n" +
            "V7F)HJ7\n" +
            "HH3)4TW\n" +
            "TMD)WXR\n" +
            "WSY)W4V\n" +
            "6P7)L4H\n" +
            "GTB)GY7\n" +
            "84P)ZYP\n" +
            "LXC)8XP\n" +
            "VK7)4L2\n" +
            "2XD)H66\n" +
            "WSV)DRP\n" +
            "25P)NR6\n" +
            "7GB)5KB\n" +
            "4YN)232\n" +
            "1PV)X5T\n" +
            "CJ5)ZKZ\n" +
            "T4N)K7Y\n" +
            "4QM)DL4\n" +
            "J83)MVC\n" +
            "Y5M)B9P\n" +
            "J4V)HNS\n" +
            "QP4)8WK\n" +
            "R1Q)8HF\n" +
            "WQL)QVX\n" +
            "8D4)ZCY\n" +
            "5M4)RB4\n" +
            "ZLC)1ZR\n" +
            "FQ5)22H\n" +
            "KDZ)M73\n" +
            "F5Q)4TS\n" +
            "P1X)8VR\n" +
            "TTZ)WFN\n" +
            "ZTC)TMR\n" +
            "K4N)JLT\n" +
            "5HY)TWV\n" +
            "Z73)Q5G\n" +
            "9CG)JH7\n" +
            "X79)9SP\n" +
            "3BD)PJZ\n" +
            "3V1)N1R\n" +
            "GR2)M9L\n" +
            "C16)LLG\n" +
            "W2G)7BX\n" +
            "3NR)NF2\n" +
            "LYN)FK4\n" +
            "4G4)GTT\n" +
            "ZLC)CTZ\n" +
            "4Z7)HJG\n" +
            "L5C)S1W\n" +
            "RZ2)9DG\n" +
            "643)M1Q\n" +
            "B1Z)7WJ\n" +
            "9D2)MQR\n" +
            "MNM)3N8\n" +
            "5MT)Z38\n" +
            "84P)K4C\n" +
            "QLG)Z83\n" +
            "2RT)97G\n" +
            "1V3)2YK\n" +
            "LD2)P13\n" +
            "3V1)1BX\n" +
            "WK3)Q7Z\n" +
            "ZVB)5MT\n" +
            "RFQ)WW4\n" +
            "CDF)V7F\n" +
            "VQ8)BSN\n" +
            "JLT)CFT\n" +
            "W9B)R89\n" +
            "NJS)385\n" +
            "HT5)7YY\n" +
            "NYX)BQB\n" +
            "G1T)5PX\n" +
            "4JD)WBB\n" +
            "D8Z)GGP\n" +
            "TVN)3R9\n" +
            "ML3)QDW\n" +
            "JB9)N5L\n" +
            "NQT)BXD\n" +
            "VNH)6HQ\n" +
            "141)H5N\n" +
            "R99)NZX\n" +
            "2RH)BTN\n" +
            "XNG)YTY\n" +
            "N1R)WKB\n" +
            "4L8)9ZL\n" +
            "F2P)N3M\n" +
            "BYF)4FL\n" +
            "2FC)41D\n" +
            "6CT)FH8\n" +
            "MXY)L1P\n" +
            "VJR)GYD\n" +
            "JWV)Q4B\n" +
            "7C2)WJP\n" +
            "MB3)XQH\n" +
            "N6J)31H\n" +
            "2SW)ZH8\n" +
            "B9P)C38\n" +
            "HBQ)B3B\n" +
            "YTY)MNY\n" +
            "FLH)RL2\n" +
            "9XV)M5F\n" +
            "PWT)86B\n" +
            "V1W)SRR\n" +
            "6HQ)FJ1\n" +
            "2HZ)ZVB\n" +
            "6C9)4MF\n" +
            "VKP)Y2D\n" +
            "41D)X5M\n" +
            "C97)WY9\n" +
            "PQ1)M15\n" +
            "GDC)YKJ\n" +
            "74P)KL5\n" +
            "7D7)WXF\n" +
            "QR3)DX9\n" +
            "2RQ)RXZ\n" +
            "QH4)SRN\n" +
            "G1V)3FL\n" +
            "MR1)ZP9\n" +
            "FJ1)1YB\n" +
            "G82)B8H\n" +
            "749)W2G\n" +
            "HXH)Q7M\n" +
            "X5Q)355\n" +
            "T9T)4RJ\n" +
            "2FM)LYN\n" +
            "21P)1CP\n" +
            "TJJ)5ZM\n" +
            "2NW)LJN\n" +
            "GGV)TTD\n" +
            "K3G)WCM\n" +
            "GMV)7S2\n" +
            "JHC)7WL\n" +
            "BWT)311\n" +
            "W87)7YW\n" +
            "9KB)H8B\n" +
            "Y6S)WK3\n" +
            "MXX)VJR\n" +
            "3VP)SS2\n" +
            "M15)DMX\n" +
            "YC5)44V\n" +
            "3J8)W8D\n" +
            "SVF)LD2\n" +
            "RW5)L1H\n" +
            "PDK)PNW\n" +
            "BBV)D4Y\n" +
            "GF6)D24\n" +
            "FSJ)WV9\n" +
            "VCN)NXX\n" +
            "W3Z)JT6\n" +
            "PJ5)4J3\n" +
            "YJM)TVN\n" +
            "866)ZW7\n" +
            "Q3T)KPJ\n" +
            "K2S)6CT\n" +
            "N6J)BJH\n" +
            "6Z2)JWF\n" +
            "XG5)JNX\n" +
            "7SF)2XK\n" +
            "311)KDR\n" +
            "72T)HJL\n" +
            "ZCP)CPQ\n" +
            "Z25)FJ6\n" +
            "MH8)GJ9\n" +
            "K6X)JB8\n" +
            "TJJ)5N6\n" +
            "XF2)KWS\n" +
            "CMK)SKK\n" +
            "NGV)FRJ\n" +
            "P8C)ZTG\n" +
            "QWT)C97\n" +
            "QY5)3GJ\n" +
            "XDB)DBT\n" +
            "6FC)QK6\n" +
            "LMP)7GB\n" +
            "B72)3TV\n" +
            "K63)WN2\n" +
            "TMW)4Z7\n" +
            "NW6)9MT\n" +
            "Q6C)3V8\n" +
            "7LP)HYH\n" +
            "SJM)HH3\n" +
            "M57)D76\n" +
            "5J2)MB3\n" +
            "YPD)Y24\n" +
            "VS7)L99\n" +
            "HW7)GGJ\n" +
            "5TS)D16\n" +
            "BYS)6TD\n" +
            "SZL)F9B\n" +
            "9C8)71K\n" +
            "8GP)VFQ\n" +
            "HFN)P3T\n" +
            "K9V)RKG\n" +
            "6QS)72T\n" +
            "SW6)6DT\n" +
            "H4H)ZFX\n" +
            "XHL)NPC\n" +
            "YLH)QLK\n" +
            "WMC)PQ8\n" +
            "PQ8)FG5\n" +
            "7GF)B61\n" +
            "SSK)631\n" +
            "G5R)3TX\n" +
            "822)G4Z\n" +
            "WNR)KS6\n" +
            "SKK)XK8\n" +
            "31H)Q4P\n" +
            "RZ7)BDQ\n" +
            "P29)9YC\n" +
            "HZX)P8C\n" +
            "2YK)RWB\n" +
            "88V)9YB\n" +
            "ZRH)HXS\n" +
            "HQC)JRW\n" +
            "T14)D6S\n" +
            "BTH)KPB\n" +
            "VTR)L1B\n" +
            "2RM)XM6\n" +
            "L15)789\n" +
            "JGH)VQ6\n" +
            "KDR)NJM\n" +
            "5VC)KWB\n" +
            "HRJ)ZH6\n" +
            "YQM)BXY\n" +
            "C31)2MJ\n" +
            "RTF)JZ4\n" +
            "MHK)GLW\n" +
            "BPJ)LKB\n" +
            "744)DF9\n" +
            "TBW)6L1\n" +
            "ZCY)F1L\n" +
            "WB7)6JK\n" +
            "K7Y)VH1\n" +
            "9MY)VKP\n" +
            "385)377\n" +
            "JQL)L34\n" +
            "SRY)ZGJ\n" +
            "7M6)B42\n" +
            "SMR)M3Z\n" +
            "V37)LDJ\n" +
            "PD8)6SG\n" +
            "VKQ)46N\n" +
            "L4H)V1W\n" +
            "KNL)TDJ\n" +
            "7MG)9LW\n" +
            "HW5)P29\n" +
            "97G)DJ7\n" +
            "T6P)1M1\n" +
            "C3Z)9NL\n" +
            "PNW)XBV\n" +
            "D29)JNB\n" +
            "4KK)CPF\n" +
            "VTJ)HCG\n" +
            "RSZ)3SS\n" +
            "MY5)6ZG\n" +
            "33L)9GR\n" +
            "3SS)18W\n" +
            "NN1)SJM\n" +
            "FJ6)2CP\n" +
            "ZHK)127\n" +
            "232)SN5\n" +
            "PSX)1G7\n" +
            "HDH)VS7\n" +
            "JM6)4QT\n" +
            "BXD)3ZJ\n" +
            "KS6)M3Y\n" +
            "HLQ)8JL\n" +
            "JWF)QHR\n" +
            "45K)P9F\n" +
            "BHH)K9V\n" +
            "46H)GJW";

    @Test
    public void testInputIsParsedIntoMap() {
        assertEquals(11, orbits.parseToMap(input).size());
    }

    @Test
    public void testParsedInputIsClean() {
        String input = "COM)B";
        assertEquals("B", orbits.getKey(input));
        assertEquals("COM", orbits.getValue(input));
    }

    @Test
    public void testNumberOfParents() {
        assertEquals(273985, orbits.calculate(orbits.parseToMap(input)));
    }
}
