package com.telesoftas.aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class OrbitsTest {

    private Orbits orbits = new Orbits();

    private String input = "VZ3)KYR\n" +
                           "71B)KMC\n" +
                           "RST)B6X\n" +
                           "T9P)91Q\n" +
                           "WLC)PGY\n" +
                           "KGW)6B2\n" +
                           "CYZ)B1P\n" +
                           "NQ8)SHS\n" +
                           "J94)4KP\n" +
                           "4ZV)GB9\n" +
                           "CDS)NVS\n" +
                           "26G)KFS\n" +
                           "3QS)Z5D\n" +
                           "N5M)WRF\n" +
                           "97Y)8F1\n" +
                           "V4H)PH6\n" +
                           "QTK)CS2\n" +
                           "CCC)Z2Y\n" +
                           "KTK)GV6\n" +
                           "Z2Y)92Z\n" +
                           "M9G)ZJ4\n" +
                           "KKC)Y7M\n" +
                           "V4X)WKQ\n" +
                           "T8V)1Q3\n" +
                           "VBQ)25K\n" +
                           "SY7)YVY\n" +
                           "BZ3)2VD\n" +
                           "6ZG)2TP\n" +
                           "3NY)JSV\n" +
                           "NPB)HQL\n" +
                           "3F4)92P\n" +
                           "3SB)R49\n" +
                           "5P4)LYK\n" +
                           "VKW)8LV\n" +
                           "8LS)814\n" +
                           "26W)17Z\n" +
                           "C4W)X2T\n" +
                           "XX9)Z4W\n" +
                           "VXG)54T\n" +
                           "LZN)D19\n" +
                           "4SL)8LY\n" +
                           "V4J)HPN\n" +
                           "YHV)M6D\n" +
                           "F7R)PYG\n" +
                           "5FX)CSR\n" +
                           "QVT)4M4\n" +
                           "L2S)6CB\n" +
                           "58X)3DY\n" +
                           "PK7)JH4\n" +
                           "SGK)WS4\n" +
                           "XMQ)3F8\n" +
                           "GFB)QHW\n" +
                           "RNM)9V5\n" +
                           "ZBQ)THN\n" +
                           "XLX)YX1\n" +
                           "HDJ)T5P\n" +
                           "KFS)NQ8\n" +
                           "P4Q)Q47\n" +
                           "JP3)WJY\n" +
                           "DT6)C9P\n" +
                           "MW5)CXF\n" +
                           "D5S)FC4\n" +
                           "1ZD)MHD\n" +
                           "YZT)BFJ\n" +
                           "DNV)JSY\n" +
                           "8WZ)YQ7\n" +
                           "25L)M5R\n" +
                           "Y8M)QFJ\n" +
                           "7L3)BNK\n" +
                           "GLD)3X8\n" +
                           "5SG)91M\n" +
                           "1BQ)5MG\n" +
                           "BZT)ZK2\n" +
                           "167)8V9\n" +
                           "C3Y)1YY\n" +
                           "85M)CRV\n" +
                           "469)RST\n" +
                           "RWS)KCK\n" +
                           "RL2)CQQ\n" +
                           "YBV)Q7S\n" +
                           "DTS)T8W\n" +
                           "LBT)FQ2\n" +
                           "SGZ)V5F\n" +
                           "PJZ)MHK\n" +
                           "TZJ)JCL\n" +
                           "Y63)N5M\n" +
                           "79F)CX6\n" +
                           "21X)97Y\n" +
                           "41J)QVD\n" +
                           "JGF)DNV\n" +
                           "TSJ)TX3\n" +
                           "RJF)MRL\n" +
                           "9BF)WHY\n" +
                           "7HB)TZV\n" +
                           "W9W)3PY\n" +
                           "K1X)YZ8\n" +
                           "19H)769\n" +
                           "CJG)6TP\n" +
                           "YZC)R9Z\n" +
                           "CL7)V81\n" +
                           "G7M)RN1\n" +
                           "2XG)9HG\n" +
                           "1DN)Z89\n" +
                           "STM)6XV\n" +
                           "LW2)34W\n" +
                           "QPH)MZP\n" +
                           "DV5)3WK\n" +
                           "86B)M8J\n" +
                           "FLC)KKN\n" +
                           "FB9)4Y5\n" +
                           "2T6)RW7\n" +
                           "4JN)PJH\n" +
                           "4KP)HNF\n" +
                           "278)B48\n" +
                           "N7K)1JD\n" +
                           "WJZ)RWS\n" +
                           "RWS)G5Q\n" +
                           "JDP)YNV\n" +
                           "17L)G6N\n" +
                           "VJN)LQP\n" +
                           "RN1)76J\n" +
                           "278)T7F\n" +
                           "HQL)FQN\n" +
                           "JTT)JK9\n" +
                           "91M)8KG\n" +
                           "G49)9NF\n" +
                           "DWP)RGR\n" +
                           "YXL)2N3\n" +
                           "QM8)B18\n" +
                           "MG2)S7P\n" +
                           "81M)K6Z\n" +
                           "N7Y)FGQ\n" +
                           "FQN)15F\n" +
                           "WSQ)41G\n" +
                           "FJ5)TZJ\n" +
                           "4QK)88V\n" +
                           "DGZ)P29\n" +
                           "WQX)C1F\n" +
                           "RZD)25L\n" +
                           "JH4)JGX\n" +
                           "DPB)8Z5\n" +
                           "3RK)1BQ\n" +
                           "WLQ)CV3\n" +
                           "F52)QXC\n" +
                           "HYQ)KBX\n" +
                           "W29)JTT\n" +
                           "K54)RZ4\n" +
                           "QHS)VR4\n" +
                           "T1M)888\n" +
                           "635)F8W\n" +
                           "17Z)95B\n" +
                           "YV7)KR1\n" +
                           "4FX)D2T\n" +
                           "HBR)SP9\n" +
                           "S7G)LYN\n" +
                           "FDM)BCL\n" +
                           "QJG)F12\n" +
                           "V5M)Q66\n" +
                           "Y9G)7SB\n" +
                           "K3V)GC4\n" +
                           "R8H)HLD\n" +
                           "MZY)K72\n" +
                           "K6N)XHS\n" +
                           "N7C)ZS9\n" +
                           "CKC)LD8\n" +
                           "FCY)K3T\n" +
                           "BBS)HNG\n" +
                           "PFR)2YJ\n" +
                           "LVD)YXR\n" +
                           "PM4)ZGK\n" +
                           "L17)DV5\n" +
                           "QM1)LJ7\n" +
                           "FMW)ZPX\n" +
                           "K7C)5MQ\n" +
                           "H5M)HJ5\n" +
                           "YHV)YGJ\n" +
                           "CC2)XW3\n" +
                           "1P1)FKX\n" +
                           "J5D)5DP\n" +
                           "W74)RFS\n" +
                           "KCK)5SG\n" +
                           "CSG)QBX\n" +
                           "Z86)PCP\n" +
                           "248)2CP\n" +
                           "XDK)7X6\n" +
                           "2YJ)2Y3\n" +
                           "M81)JCF\n" +
                           "LL4)QTK\n" +
                           "5JF)DGQ\n" +
                           "QYM)QRZ\n" +
                           "9L6)DLC\n" +
                           "529)R5C\n" +
                           "MWH)8PP\n" +
                           "DWL)7QR\n" +
                           "Y4B)TP2\n" +
                           "5SL)W29\n" +
                           "7XN)YF5\n" +
                           "1JV)LH5\n" +
                           "GWJ)RCJ\n" +
                           "FCS)5P7\n" +
                           "ZFQ)57Q\n" +
                           "8NL)GG5\n" +
                           "N55)DM6\n" +
                           "NYG)YXN\n" +
                           "3NX)YZV\n" +
                           "NND)WTK\n" +
                           "D6F)GWJ\n" +
                           "H3C)9M1\n" +
                           "TXS)P2C\n" +
                           "NH2)343\n" +
                           "X22)CKC\n" +
                           "1JH)G24\n" +
                           "FQ2)DWW\n" +
                           "PZ2)DW7\n" +
                           "S1H)5KG\n" +
                           "KTG)5NM\n" +
                           "3KW)FWW\n" +
                           "22M)YDY\n" +
                           "YFF)DDY\n" +
                           "BD8)3WQ\n" +
                           "CS2)SXJ\n" +
                           "J31)DG2\n" +
                           "4DC)PLL\n" +
                           "DMC)RX9\n" +
                           "VQ4)GDX\n" +
                           "RX9)CL7\n" +
                           "VTL)NL3\n" +
                           "GQR)SCL\n" +
                           "YZF)HQK\n" +
                           "4LC)LQD\n" +
                           "JLS)FMW\n" +
                           "DSQ)W6Q\n" +
                           "BV7)RLM\n" +
                           "T7F)S36\n" +
                           "RMR)CBH\n" +
                           "5Y7)T9P\n" +
                           "XR3)Z81\n" +
                           "965)WDG\n" +
                           "MZC)8KN\n" +
                           "GTL)HQN\n" +
                           "RDH)Z99\n" +
                           "9NF)4FX\n" +
                           "X33)SN6\n" +
                           "L88)LZG\n" +
                           "9HG)56V\n" +
                           "VWB)BD8\n" +
                           "Q1M)17L\n" +
                           "NNH)YK1\n" +
                           "SFK)N9N\n" +
                           "KRZ)2LF\n" +
                           "F5B)6W9\n" +
                           "M9C)1NP\n" +
                           "ZS9)JQS\n" +
                           "M27)Y32\n" +
                           "SQ6)RVV\n" +
                           "DGQ)WW4\n" +
                           "M8F)P3Q\n" +
                           "7YJ)X58\n" +
                           "8V9)7L3\n" +
                           "GS7)VZ9\n" +
                           "RZV)NS2\n" +
                           "FKJ)4WF\n" +
                           "YV8)646\n" +
                           "6JH)88Q\n" +
                           "LW5)5Z7\n" +
                           "DW1)26W\n" +
                           "WN2)CWD\n" +
                           "24F)CBN\n" +
                           "4TC)Y7Z\n" +
                           "SGG)73D\n" +
                           "Q7M)MDS\n" +
                           "GYM)ZH3\n" +
                           "C5B)SWB\n" +
                           "3W2)F6V\n" +
                           "QZD)PXP\n" +
                           "2TP)4CR\n" +
                           "CX6)SNV\n" +
                           "6T1)GGD\n" +
                           "S3S)CPF\n" +
                           "CZ5)3NQ\n" +
                           "ZSM)57R\n" +
                           "F5B)MKM\n" +
                           "VM8)64G\n" +
                           "4CW)X33\n" +
                           "DJW)J5D\n" +
                           "LLW)8ZF\n" +
                           "21G)G6C\n" +
                           "XGZ)81M\n" +
                           "XVQ)TZH\n" +
                           "FGQ)NPV\n" +
                           "2HN)DR9\n" +
                           "NSK)7BC\n" +
                           "KH2)278\n" +
                           "GH2)1DD\n" +
                           "JVM)154\n" +
                           "WQ6)2DN\n" +
                           "JD9)DSQ\n" +
                           "SJX)33W\n" +
                           "37N)7W6\n" +
                           "JV3)KTG\n" +
                           "SRG)NWN\n" +
                           "GJQ)9J9\n" +
                           "NFF)46K\n" +
                           "5HD)ZJY\n" +
                           "8T6)Q59\n" +
                           "2CT)T59\n" +
                           "FH7)4XY\n" +
                           "C5B)7XX\n" +
                           "9L6)YBV\n" +
                           "CQQ)17R\n" +
                           "HJ5)JDP\n" +
                           "FTL)4DD\n" +
                           "7KW)MZC\n" +
                           "HVV)P63\n" +
                           "7WM)46M\n" +
                           "39Z)LRV\n" +
                           "PYG)LYP\n" +
                           "DM6)FS8\n" +
                           "KDZ)S7X\n" +
                           "NVS)Y4H\n" +
                           "37V)573\n" +
                           "ZS1)83C\n" +
                           "9DM)Y8G\n" +
                           "M5R)HYT\n" +
                           "WTK)529\n" +
                           "67D)LC5\n" +
                           "4WF)564\n" +
                           "7K6)MKL\n" +
                           "VZN)Q17\n" +
                           "GNP)7XN\n" +
                           "JLY)B86\n" +
                           "8Z7)XSK\n" +
                           "Y8M)QBD\n" +
                           "6NX)XD2\n" +
                           "TX3)JVM\n" +
                           "X4N)62D\n" +
                           "61P)44Y\n" +
                           "J35)ZWX\n" +
                           "7PT)S3S\n" +
                           "FWW)Y6J\n" +
                           "WLN)2BP\n" +
                           "Y1T)GLD\n" +
                           "F8W)CKT\n" +
                           "7LH)S2J\n" +
                           "BFJ)XMQ\n" +
                           "Z7P)2XG\n" +
                           "Y89)886\n" +
                           "5K8)5FW\n" +
                           "JP1)QQL\n" +
                           "2P1)635\n" +
                           "ZDD)2HN\n" +
                           "NH6)CY7\n" +
                           "8Z4)1JV\n" +
                           "NJC)CRZ\n" +
                           "GXB)1RB\n" +
                           "W1F)G2W\n" +
                           "76P)GF8\n" +
                           "B8X)F52\n" +
                           "TM1)HJT\n" +
                           "X6J)P1C\n" +
                           "1XD)WDQ\n" +
                           "4D1)NNH\n" +
                           "TS5)FRL\n" +
                           "6LX)17G\n" +
                           "L5F)QM8\n" +
                           "84Q)RH8\n" +
                           "CTF)72Y\n" +
                           "XGJ)39Z\n" +
                           "W7F)9L6\n" +
                           "QNQ)MR9\n" +
                           "H31)QQV\n" +
                           "8LY)ZFH\n" +
                           "26H)BZ3\n" +
                           "K6Z)X5T\n" +
                           "M4N)9NV\n" +
                           "Y2Q)WQB\n" +
                           "WVZ)VWB\n" +
                           "JB4)HQR\n" +
                           "6VJ)2D8\n" +
                           "MCN)SGZ\n" +
                           "YNG)1DS\n" +
                           "P4Q)QHS\n" +
                           "KBW)BH9\n" +
                           "51Y)M44\n" +
                           "8KG)JWX\n" +
                           "M81)PKQ\n" +
                           "VTN)K54\n" +
                           "4KV)BJH\n" +
                           "DPR)GHC\n" +
                           "SFM)T1P\n" +
                           "JCF)2S6\n" +
                           "1L2)8W1\n" +
                           "XN8)HVM\n" +
                           "GCW)2BH\n" +
                           "KNQ)P51\n" +
                           "X9H)G49\n" +
                           "L19)S7G\n" +
                           "LSC)VB8\n" +
                           "G4S)JHN\n" +
                           "44C)9RL\n" +
                           "PR9)7RD\n" +
                           "DQC)VZ3\n" +
                           "8HH)WST\n" +
                           "TJM)8Z2\n" +
                           "88N)3QP\n" +
                           "5YC)7GR\n" +
                           "V7Y)S5J\n" +
                           "67F)8LS\n" +
                           "YDY)Z5X\n" +
                           "LSB)K1L\n" +
                           "DX1)G3X\n" +
                           "1MV)S3Q\n" +
                           "9YT)NX2\n" +
                           "QM3)CJG\n" +
                           "WJY)28T\n" +
                           "JKJ)KWC\n" +
                           "H8S)CYZ\n" +
                           "LPN)D3L\n" +
                           "MZ4)65Y\n" +
                           "7LK)WPB\n" +
                           "ZNH)W9C\n" +
                           "HR9)NH2\n" +
                           "LM4)22M\n" +
                           "L2S)N76\n" +
                           "V6X)QFR\n" +
                           "S47)SGG\n" +
                           "N2Z)XLX\n" +
                           "6QR)84Q\n" +
                           "C6P)Z7P\n" +
                           "RFS)Q61\n" +
                           "NX2)H5Y\n" +
                           "G6V)ZSM\n" +
                           "RGX)1Z2\n" +
                           "XN8)MZN\n" +
                           "D4Y)NMN\n" +
                           "K4Q)V8Z\n" +
                           "N46)RH6\n" +
                           "F1N)WC8\n" +
                           "D3L)LM4\n" +
                           "K9Q)469\n" +
                           "C9C)72P\n" +
                           "Z78)X6R\n" +
                           "BML)2N2\n" +
                           "SWB)6YY\n" +
                           "P63)N3J\n" +
                           "WSH)47C\n" +
                           "7GR)2QR\n" +
                           "D2T)BC6\n" +
                           "LG4)7BN\n" +
                           "X5X)8BB\n" +
                           "5YR)215\n" +
                           "T59)TRF\n" +
                           "T1P)NC8\n" +
                           "24R)M9B\n" +
                           "ZZ3)1SX\n" +
                           "H88)PZ2\n" +
                           "MR9)CDT\n" +
                           "5CZ)9GC\n" +
                           "7YB)RGX\n" +
                           "RLW)HYH\n" +
                           "NYK)X3Y\n" +
                           "H5Q)PYD\n" +
                           "YXR)TM1\n" +
                           "K4Q)BQB\n" +
                           "9VY)32D\n" +
                           "1P1)8BM\n" +
                           "MHK)J3P\n" +
                           "ZFQ)FV2\n" +
                           "2MJ)XFJ\n" +
                           "FC4)32C\n" +
                           "SBQ)HLZ\n" +
                           "LYK)WN2\n" +
                           "L23)WZ9\n" +
                           "1BZ)ZWB\n" +
                           "YK1)HMJ\n" +
                           "489)CWP\n" +
                           "VS8)HYQ\n" +
                           "PCP)281\n" +
                           "F41)J94\n" +
                           "QHX)KZ1\n" +
                           "69L)4M5\n" +
                           "9P1)62P\n" +
                           "PY2)DQV\n" +
                           "BLH)M27\n" +
                           "3K5)QZD\n" +
                           "Y96)PKC\n" +
                           "QQP)HDS\n" +
                           "TGD)HD1\n" +
                           "YQT)N33\n" +
                           "4HB)TX4\n" +
                           "7BC)K59\n" +
                           "P13)9ZQ\n" +
                           "MP3)67F\n" +
                           "W9C)KN6\n" +
                           "9XM)LW2\n" +
                           "Z89)JV3\n" +
                           "H3J)XGZ\n" +
                           "4KV)TP4\n" +
                           "233)NH6\n" +
                           "GGD)YV8\n" +
                           "3PW)DVH\n" +
                           "V81)4N7\n" +
                           "7X6)4VB\n" +
                           "N28)ZCL\n" +
                           "JLS)4JN\n" +
                           "Q59)F41\n" +
                           "5LN)P9G\n" +
                           "WDG)ZH9\n" +
                           "8BB)GTG\n" +
                           "S7P)JZ7\n" +
                           "YB6)WXX\n" +
                           "VCM)M1S\n" +
                           "FVG)51Y\n" +
                           "CWK)VG8\n" +
                           "P96)VQ4\n" +
                           "GS7)LLW\n" +
                           "313)5NV\n" +
                           "ZPG)H5M\n" +
                           "L2V)GJS\n" +
                           "2C3)N28\n" +
                           "JYN)2S4\n" +
                           "KPC)H3C\n" +
                           "JZ7)HV8\n" +
                           "88N)3JQ\n" +
                           "6DD)THF\n" +
                           "MQS)ZBQ\n" +
                           "1DD)3KD\n" +
                           "L6D)QRT\n" +
                           "L96)KBK\n" +
                           "FS8)KTK\n" +
                           "GHC)6DD\n" +
                           "TJL)N3H\n" +
                           "YR2)W7F\n" +
                           "1Q3)TGD\n" +
                           "P85)JD9\n" +
                           "97P)CH1\n" +
                           "215)Z7V\n" +
                           "PG3)7BF\n" +
                           "JN8)7DM\n" +
                           "S3Q)NYK\n" +
                           "QTH)ZS4\n" +
                           "XDT)N7K\n" +
                           "D6T)4SL\n" +
                           "S3S)227\n" +
                           "2ZW)X5R\n" +
                           "RH8)P8D\n" +
                           "FMQ)YZT\n" +
                           "RTT)PNL\n" +
                           "5P7)1QH\n" +
                           "KZ1)8Z7\n" +
                           "2LS)HRX\n" +
                           "ZG6)K7K\n" +
                           "7LH)3RK\n" +
                           "4N7)V4J\n" +
                           "ZYG)L88\n" +
                           "BXK)GWP\n" +
                           "KVF)KH9\n" +
                           "S2J)L2S\n" +
                           "Z4Y)241\n" +
                           "32C)FH8\n" +
                           "5BY)WSQ\n" +
                           "THF)HTQ\n" +
                           "573)SFX\n" +
                           "VXY)1GQ\n" +
                           "7J9)FCS\n" +
                           "2TF)FCY\n" +
                           "ZYP)C3Y\n" +
                           "XQ1)H5Q\n" +
                           "ZGD)313\n" +
                           "2WF)SFM\n" +
                           "1SX)YNG\n" +
                           "CNT)QNQ\n" +
                           "M65)3F9\n" +
                           "CRL)2TF\n" +
                           "LK4)TS5\n" +
                           "DB6)PWW\n" +
                           "NPV)7JQ\n" +
                           "Q3N)WYH\n" +
                           "1CK)JMJ\n" +
                           "HY8)2ZW\n" +
                           "Z78)HTV\n" +
                           "S5X)V7W\n" +
                           "B18)Z6F\n" +
                           "718)VF8\n" +
                           "Q7S)7YJ\n" +
                           "W73)1MC\n" +
                           "YZX)YPW\n" +
                           "YC8)SGY\n" +
                           "HMJ)DPB\n" +
                           "G8H)2FD\n" +
                           "K59)5K8\n" +
                           "245)DQC\n" +
                           "ZX4)FV9\n" +
                           "HNG)9QK\n" +
                           "SVT)SB2\n" +
                           "JF8)2M8\n" +
                           "7K7)CHJ\n" +
                           "KBV)DCV\n" +
                           "KDQ)446\n" +
                           "VMJ)8SL\n" +
                           "26D)Y63\n" +
                           "9Q9)X2R\n" +
                           "KMC)5XT\n" +
                           "2BH)NKG\n" +
                           "MH8)954\n" +
                           "VJD)7YP\n" +
                           "2QR)D9B\n" +
                           "9PJ)Y89\n" +
                           "TZ4)W9Y\n" +
                           "397)TZK\n" +
                           "ZPR)WLN\n" +
                           "JNY)2ZV\n" +
                           "CVM)4V7\n" +
                           "XWM)NPG\n" +
                           "TZK)8NL\n" +
                           "1YJ)PBG\n" +
                           "4CB)16R\n" +
                           "C4C)88N\n" +
                           "CBH)X6J\n" +
                           "281)GWC\n" +
                           "Y1J)965\n" +
                           "6W4)8YF\n" +
                           "R2L)XN3\n" +
                           "SP4)8ZW\n" +
                           "TML)PDM\n" +
                           "2MQ)NFF\n" +
                           "ZJ4)V5M\n" +
                           "CXF)26H\n" +
                           "XRG)WNM\n" +
                           "7XX)PL5\n" +
                           "9V5)7GJ\n" +
                           "5NM)9PJ\n" +
                           "RQ5)GMY\n" +
                           "BQB)VXG\n" +
                           "154)99Q\n" +
                           "KKN)7WM\n" +
                           "K3P)YOU\n" +
                           "K2R)YZC\n" +
                           "M3P)489\n" +
                           "4XX)CWK\n" +
                           "LRV)D4Y\n" +
                           "HW5)MFD\n" +
                           "YM3)S1H\n" +
                           "5DP)8ZJ\n" +
                           "TKC)YNQ\n" +
                           "KZ1)KG7\n" +
                           "COM)7J9\n" +
                           "LZW)4PS\n" +
                           "6TP)38J\n" +
                           "3JZ)KBZ\n" +
                           "YM4)X9H\n" +
                           "N5Z)X1V\n" +
                           "KR1)1TT\n" +
                           "B1P)TZ4\n" +
                           "G7Y)FHX\n" +
                           "TNN)4CN\n" +
                           "LC5)PK7\n" +
                           "241)MP3\n" +
                           "HQR)K6G\n" +
                           "PLL)BBZ\n" +
                           "FBD)VRG\n" +
                           "LJ7)1ZR\n" +
                           "JCL)YM3\n" +
                           "47F)9W6\n" +
                           "7BN)TML\n" +
                           "HYT)HC8\n" +
                           "Z4W)C9C\n" +
                           "6HC)JH7\n" +
                           "Z6X)J35\n" +
                           "DQ1)D8B\n" +
                           "RLM)D6Y\n" +
                           "K73)47F\n" +
                           "WPB)TH6\n" +
                           "CJT)WLQ\n" +
                           "67D)L9S\n" +
                           "Y5X)J44\n" +
                           "NBQ)2FB\n" +
                           "TX3)Q5R\n" +
                           "CH1)565\n" +
                           "2S4)PSV\n" +
                           "HSY)QHX\n" +
                           "V5R)Y71\n" +
                           "YQT)1XD\n" +
                           "1DS)J5Z\n" +
                           "JH7)MGW\n" +
                           "7SB)WSH\n" +
                           "PX3)56Q\n" +
                           "ZPX)H57\n" +
                           "TP2)6XX\n" +
                           "WC8)M65\n" +
                           "H1L)GJQ\n" +
                           "7JQ)FB9\n" +
                           "X5R)CC2\n" +
                           "GWP)QPX\n" +
                           "FC4)MQS\n" +
                           "8SL)TK9\n" +
                           "PKQ)KNC\n" +
                           "PBN)2LS\n" +
                           "NT9)PJZ\n" +
                           "2FD)HR9\n" +
                           "RZ4)CTF\n" +
                           "HQN)BTP\n" +
                           "4N7)NSK\n" +
                           "DVK)928\n" +
                           "ZPP)XWM\n" +
                           "C57)LLC\n" +
                           "DFV)H3J\n" +
                           "92M)L17\n" +
                           "8D7)B68\n" +
                           "D19)MC4\n" +
                           "C6D)QM1\n" +
                           "QVD)Z1M\n" +
                           "DVR)71B\n" +
                           "17R)6HD\n" +
                           "C1F)74Y\n" +
                           "J5Q)41J\n" +
                           "S5R)9BF\n" +
                           "1YY)G8H\n" +
                           "VRK)F93\n" +
                           "YQ7)ZG6\n" +
                           "L8G)HT1\n" +
                           "BRJ)SHP\n" +
                           "RVV)WX4\n" +
                           "4QM)4DC\n" +
                           "JSV)YR2\n" +
                           "YDZ)K31\n" +
                           "XHS)L6D\n" +
                           "8LV)8T6\n" +
                           "NVR)775\n" +
                           "5JQ)SWZ\n" +
                           "D5G)R5K\n" +
                           "ZFH)YP1\n" +
                           "CQY)K4Q\n" +
                           "LRD)718\n" +
                           "1DM)ZS1\n" +
                           "P29)12D\n" +
                           "WXX)8DK\n" +
                           "L4M)3B7\n" +
                           "RZH)ZZ3\n" +
                           "76J)S5X\n" +
                           "PYD)QQB\n" +
                           "NC8)GCH\n" +
                           "HRX)4QK\n" +
                           "GQ4)69L\n" +
                           "ZHQ)F1N\n" +
                           "MRL)21G\n" +
                           "V62)1C9\n" +
                           "3JQ)HY8\n" +
                           "QKB)1L2\n" +
                           "WY9)ZDD\n" +
                           "CWZ)HMF\n" +
                           "FV9)MZY\n" +
                           "2M8)W7J\n" +
                           "QXC)YBT\n" +
                           "N33)DJW\n" +
                           "74Y)95T\n" +
                           "62P)YKY\n" +
                           "YP1)2MQ\n" +
                           "22M)3C5\n" +
                           "DVJ)JS4\n" +
                           "9NF)4KV\n" +
                           "17G)L4M\n" +
                           "63Y)1P1\n" +
                           "BC6)VBQ\n" +
                           "7CW)PQG\n" +
                           "6W9)WRJ\n" +
                           "97Z)81B\n" +
                           "VPP)3NX\n" +
                           "VNM)KYB\n" +
                           "QCB)BF6\n" +
                           "CKT)1ZD\n" +
                           "2BP)VMD\n" +
                           "ZQD)QM3\n" +
                           "GDV)KN1\n" +
                           "2HD)25Y\n" +
                           "Y4H)HZ5\n" +
                           "KN6)4D1\n" +
                           "PKQ)LSC\n" +
                           "JS4)L86\n" +
                           "MX6)B51\n" +
                           "9MD)3LR\n" +
                           "2VD)LCD\n" +
                           "7RG)GQR\n" +
                           "VB8)4CW\n" +
                           "YLL)3SB\n" +
                           "YBT)GTX\n" +
                           "B6Z)Y8S\n" +
                           "1YB)JLS\n" +
                           "5SL)BTH\n" +
                           "3KD)PL9\n" +
                           "YNQ)JFL\n" +
                           "3T2)VYV\n" +
                           "ZWB)62C\n" +
                           "J3N)39T\n" +
                           "5Z7)J1R\n" +
                           "WYY)D6T\n" +
                           "YX1)RTT\n" +
                           "P94)6T1\n" +
                           "JMJ)MH8\n" +
                           "1RB)ZGD\n" +
                           "7DM)4QM\n" +
                           "QFG)CMY\n" +
                           "7KY)CT1\n" +
                           "X9S)J6D\n" +
                           "PBN)3PW\n" +
                           "RT5)Q7M\n" +
                           "8BM)9YT\n" +
                           "THN)JWN\n" +
                           "DVH)JLY\n" +
                           "N7L)F7R\n" +
                           "GDX)CRL\n" +
                           "C7Z)7KW\n" +
                           "TK9)NM3\n" +
                           "HYG)7K7\n" +
                           "QVP)71T\n" +
                           "DV7)1YH\n" +
                           "TZV)Z6C\n" +
                           "KBL)QK1\n" +
                           "W7J)Y8M\n" +
                           "JNL)JP1\n" +
                           "KR1)L2B\n" +
                           "X1K)21L\n" +
                           "B26)ZPR\n" +
                           "3QP)LZW\n" +
                           "Z1M)TNN\n" +
                           "WHY)THJ\n" +
                           "YNV)ZHN\n" +
                           "LV9)JNY\n" +
                           "JWS)V4Q\n" +
                           "1LZ)PBN\n" +
                           "58F)HYG\n" +
                           "BT7)7PD\n" +
                           "Y8S)WQX\n" +
                           "Q66)2MJ\n" +
                           "769)KYK\n" +
                           "FLH)1JH\n" +
                           "FCB)G35\n" +
                           "VML)JRL\n" +
                           "DGZ)Z86\n" +
                           "PWJ)63G\n" +
                           "3VF)2T6\n" +
                           "HJZ)L8G\n" +
                           "NPG)CJC\n" +
                           "7T4)4N1\n" +
                           "9QK)KPC\n" +
                           "QQL)NHX\n" +
                           "L6L)91S\n" +
                           "81B)TXS\n" +
                           "25Y)KBV\n" +
                           "4QQ)H74\n" +
                           "FB9)NVR\n" +
                           "QN3)VTL\n" +
                           "QTH)P96\n" +
                           "1C9)D9Q\n" +
                           "MFD)F5B\n" +
                           "343)9D6\n" +
                           "9GQ)V62\n" +
                           "STM)X88\n" +
                           "M9B)GQ4\n" +
                           "4V7)CS4\n" +
                           "JFL)3WG\n" +
                           "JPV)6H5\n" +
                           "XJC)C5T\n" +
                           "CRZ)W74\n" +
                           "XLZ)BRJ\n" +
                           "L86)4FH\n" +
                           "1DD)WSR\n" +
                           "182)1BZ\n" +
                           "DNN)FVQ\n" +
                           "9M1)PG1\n" +
                           "M9B)58X\n" +
                           "D6Y)J4H\n" +
                           "PDM)QPQ\n" +
                           "GMY)LF7\n" +
                           "YXX)37V\n" +
                           "4R5)KXL\n" +
                           "FHX)NPB\n" +
                           "CHJ)PYM\n" +
                           "ZWX)V5R\n" +
                           "9BV)ZDW\n" +
                           "D9Y)HVV\n" +
                           "TJM)79C\n" +
                           "PKC)BW5\n" +
                           "3T5)61P\n" +
                           "W6Q)1LZ\n" +
                           "CVB)1SN\n" +
                           "8TV)8QB\n" +
                           "52B)WK2\n" +
                           "886)HYC\n" +
                           "XTP)WJZ\n" +
                           "6B2)PWJ\n" +
                           "SH2)ZLH\n" +
                           "PTZ)VS7\n" +
                           "CMY)8D7\n" +
                           "JK9)67D\n" +
                           "GTG)BXK\n" +
                           "4RG)8Z1\n" +
                           "PNL)J3N\n" +
                           "62C)VRK\n" +
                           "HBR)3QS\n" +
                           "ZK2)64K\n" +
                           "S7X)P59\n" +
                           "QDC)6XD\n" +
                           "HTQ)7ZV\n" +
                           "Q8R)Y4B\n" +
                           "BNK)JMC\n" +
                           "2QR)Z78\n" +
                           "ZH3)2G5\n" +
                           "YSB)1MV\n" +
                           "X58)KKC\n" +
                           "V4J)JTC\n" +
                           "YPW)FLH\n" +
                           "8YF)RZX\n" +
                           "N46)FFK\n" +
                           "LSB)Y4Y\n" +
                           "L36)B6Z\n" +
                           "4PS)RZV\n" +
                           "D9K)STM\n" +
                           "RCJ)D9K\n" +
                           "WYH)V6X\n" +
                           "Y6J)3DW\n" +
                           "2T8)PX3\n" +
                           "2N3)1DN\n" +
                           "64G)3JX\n" +
                           "QBX)7T4\n" +
                           "3VF)HJQ\n" +
                           "WK2)21X\n" +
                           "ZGD)6K6\n" +
                           "G9F)K4V\n" +
                           "LQH)638\n" +
                           "JFF)GLT\n" +
                           "5S4)9XM\n" +
                           "8DK)2HD\n" +
                           "NL3)LG4\n" +
                           "92P)VRW\n" +
                           "BGF)5BY\n" +
                           "3QS)YQT\n" +
                           "81M)ZPG\n" +
                           "YKY)GNP\n" +
                           "P9G)6VJ\n" +
                           "FK1)F22\n" +
                           "64K)YKL\n" +
                           "PSV)397\n" +
                           "3LR)P78\n" +
                           "NM3)6NX\n" +
                           "HD1)RWB\n" +
                           "R11)963\n" +
                           "4HK)B96\n" +
                           "LNL)4QQ\n" +
                           "NMZ)2R8\n" +
                           "MGW)XT2\n" +
                           "9GC)3T5\n" +
                           "8WX)1C1\n" +
                           "G7M)MTB\n" +
                           "Q47)LNM\n" +
                           "BNK)GK3\n" +
                           "SCL)RYF\n" +
                           "4VB)182\n" +
                           "6H5)PY2\n" +
                           "QHX)BBS\n" +
                           "RSX)2TH\n" +
                           "GY2)Y2Q\n" +
                           "47C)C72\n" +
                           "MPF)VHF\n" +
                           "SML)DWP\n" +
                           "JHN)XLZ\n" +
                           "N3J)XDT\n" +
                           "9W6)H3L\n" +
                           "78B)SP4\n" +
                           "TN1)6ST\n" +
                           "9VW)YXL\n" +
                           "D6B)6QR\n" +
                           "QZC)YDZ\n" +
                           "DT6)8HH\n" +
                           "WNF)ZNH\n" +
                           "RTT)44C\n" +
                           "TJR)JNL\n" +
                           "MK7)8TV\n" +
                           "658)QFG\n" +
                           "DWW)RMD\n" +
                           "ZWF)QVP\n" +
                           "9JB)6JH\n" +
                           "JSY)NYG\n" +
                           "YC6)HDJ\n" +
                           "2N2)TJR\n" +
                           "HTK)FCB\n" +
                           "1NP)LKM\n" +
                           "QRT)ZFQ\n" +
                           "91Q)PV7\n" +
                           "689)VMJ\n" +
                           "21L)ZHQ\n" +
                           "ZTD)XQ7\n" +
                           "7GR)CFW\n" +
                           "58X)4R5\n" +
                           "WGC)WDZ\n" +
                           "G2W)2P1\n" +
                           "DQF)LW5\n" +
                           "725)C6P\n" +
                           "3LZ)6FJ\n" +
                           "3JX)TKY\n" +
                           "JL1)SGK\n" +
                           "JMC)7LQ\n" +
                           "5MF)TMD\n" +
                           "1FP)1Y5\n" +
                           "MXK)Q1M\n" +
                           "DB4)DVJ\n" +
                           "BCL)6VS\n" +
                           "B96)ZQH\n" +
                           "FLC)B73\n" +
                           "2R8)F8N\n" +
                           "BBZ)B8X\n" +
                           "88V)X1K\n" +
                           "XSX)6C8\n" +
                           "ZVP)RBT\n" +
                           "634)NVJ\n" +
                           "8Z2)DMC\n" +
                           "S5J)J5Q\n" +
                           "D28)25F\n" +
                           "MZP)9MS\n" +
                           "1JD)W7B\n" +
                           "7W6)N71\n" +
                           "BTP)5YC\n" +
                           "CSR)KH2\n" +
                           "6XD)LZB\n" +
                           "8HT)VJD\n" +
                           "Z7P)GLR\n" +
                           "QHW)3J7\n" +
                           "ZS4)NT9\n" +
                           "GDX)L36\n" +
                           "L9Q)WY9\n" +
                           "BTQ)MG2\n" +
                           "DR9)YZS\n" +
                           "Z6F)PHM\n" +
                           "LYP)BFW\n" +
                           "ZJY)PG3\n" +
                           "PQG)1CK\n" +
                           "92Z)P85\n" +
                           "M6N)KNQ\n" +
                           "MMT)H88\n" +
                           "8S2)M8F\n" +
                           "7LQ)3K5\n" +
                           "2LF)6LX\n" +
                           "L3X)R55\n" +
                           "6ZZ)QFB\n" +
                           "BFW)W9W\n" +
                           "62P)S47\n" +
                           "8X2)K73\n" +
                           "Y32)NMZ\n" +
                           "34W)XGJ\n" +
                           "GB9)93G\n" +
                           "PNV)Y1T\n" +
                           "63V)7LH\n" +
                           "3SD)VM8\n" +
                           "N76)VZN\n" +
                           "DV5)L2V\n" +
                           "N6K)K3M\n" +
                           "4DD)YZG\n" +
                           "16R)L5F\n" +
                           "7BF)GCW\n" +
                           "ZCL)KRZ\n" +
                           "RML)7KY\n" +
                           "RQ4)8PK\n" +
                           "X1V)2T8\n" +
                           "3WK)79F\n" +
                           "GWC)PTZ\n" +
                           "ZDW)ZQD\n" +
                           "3WG)HSY\n" +
                           "RWB)DTS\n" +
                           "C72)KVN\n" +
                           "B48)C6D\n" +
                           "4N1)WP6\n" +
                           "6YY)97P\n" +
                           "XYT)XRG\n" +
                           "GF8)F8C\n" +
                           "XFV)9DM\n" +
                           "1C1)QVT\n" +
                           "WP6)R2L\n" +
                           "SHP)BLH\n" +
                           "J1R)6HG\n" +
                           "12D)ZS8\n" +
                           "4BW)D9S\n" +
                           "ZGK)6Q7\n" +
                           "HYH)GFB\n" +
                           "7PB)233\n" +
                           "6HD)Q3N\n" +
                           "4M5)B84\n" +
                           "NSK)7YB\n" +
                           "NPV)5S4\n" +
                           "4RR)CVB\n" +
                           "QK1)1YB\n" +
                           "XZJ)7K6\n" +
                           "WWJ)ZPP\n" +
                           "LQD)PS3\n" +
                           "33W)XFV\n" +
                           "K6G)KKR\n" +
                           "CXW)658\n" +
                           "K7C)5Y7\n" +
                           "MHD)56G\n" +
                           "2CP)41X\n" +
                           "HLD)HBR\n" +
                           "92B)NBQ\n" +
                           "PWW)R6X\n" +
                           "R55)6DR\n" +
                           "G35)PM4\n" +
                           "VG8)D5S\n" +
                           "QNT)DT6\n" +
                           "6GC)DV7\n" +
                           "91Q)DJ6\n" +
                           "T1M)4G5\n" +
                           "JFP)XVQ\n" +
                           "WDS)CJT\n" +
                           "JWX)NYQ\n" +
                           "NPS)TCR\n" +
                           "XPC)331\n" +
                           "P8D)JPV\n" +
                           "Z99)N55\n" +
                           "THJ)YV7\n" +
                           "JTC)VJN\n" +
                           "ZQQ)JR9\n" +
                           "25Q)5TF\n" +
                           "XD7)WNF\n" +
                           "2TP)MYL\n" +
                           "CFW)XXX\n" +
                           "88Q)KVB\n" +
                           "NT9)TJL\n" +
                           "JR9)7HB\n" +
                           "L6Y)H24\n" +
                           "4M4)WVZ\n" +
                           "TLV)MXK\n" +
                           "4CN)S5D\n" +
                           "R49)DX1\n" +
                           "YD1)8HT\n" +
                           "8F1)X51\n" +
                           "KX9)CBY\n" +
                           "L2Z)M6N\n" +
                           "KNC)9GQ\n" +
                           "NMG)Y9G\n" +
                           "JCB)BCB\n" +
                           "8Z1)XX9\n" +
                           "LCD)5TV\n" +
                           "B73)B26\n" +
                           "XV5)MG3\n" +
                           "3J7)KDQ\n" +
                           "BJH)CSG\n" +
                           "ZHN)3JZ\n" +
                           "S5D)VML\n" +
                           "C9P)DXF\n" +
                           "HJZ)9BV\n" +
                           "46K)3SD\n" +
                           "HV8)FJR\n" +
                           "3F8)N6K\n" +
                           "KHR)9TR\n" +
                           "5TF)DPR\n" +
                           "5K8)QNT\n" +
                           "3T2)BTQ\n" +
                           "25K)KY3\n" +
                           "6CB)K7C\n" +
                           "1SN)C5B\n" +
                           "X87)RLW\n" +
                           "D9S)6GC\n" +
                           "C81)SML\n" +
                           "8W1)SQ6\n" +
                           "K72)XSR\n" +
                           "6XV)C7Z\n" +
                           "5KG)LZN\n" +
                           "WST)6PZ\n" +
                           "W9Y)4K1\n" +
                           "3F4)9VY\n" +
                           "2ZV)QMK\n" +
                           "RLM)Z3P\n" +
                           "YZV)248\n" +
                           "RBT)MZ2\n" +
                           "7CW)JFP\n" +
                           "R5K)LV9\n" +
                           "VZ9)QCB\n" +
                           "L2R)C4W\n" +
                           "VRW)QN3\n" +
                           "72Y)25Q\n" +
                           "ZH9)3NY\n" +
                           "MYL)G4S\n" +
                           "HT1)L19\n" +
                           "XSK)9JB\n" +
                           "X13)4RG\n" +
                           "HDS)BML\n" +
                           "7K6)92B\n" +
                           "V8Z)GY2\n" +
                           "PKC)XQ1\n" +
                           "Q61)RNM\n" +
                           "Z6C)6W4\n" +
                           "CJC)28Q\n" +
                           "ZQH)LNL\n" +
                           "CY7)PJD\n" +
                           "J6D)ZYG\n" +
                           "TCR)WYY\n" +
                           "L2B)5JF\n" +
                           "B6X)8X5\n" +
                           "3Z2)4BW\n" +
                           "5VG)L2Z\n" +
                           "W9Y)725\n" +
                           "JQS)76P\n" +
                           "G6V)VS8\n" +
                           "56V)DNN\n" +
                           "CBY)7RG\n" +
                           "BF6)LFF\n" +
                           "YGL)L6L\n" +
                           "XLX)23P\n" +
                           "KH9)5YR\n" +
                           "KVB)XN8\n" +
                           "YF5)SFK\n" +
                           "NP1)YXX\n" +
                           "3B7)CXW\n" +
                           "6DR)2SK\n" +
                           "Y8G)X87\n" +
                           "VWG)CWZ\n" +
                           "15F)BT7\n" +
                           "FQP)3LJ\n" +
                           "V4Q)QHR\n" +
                           "VL3)N46\n" +
                           "PGY)ZYD\n" +
                           "87K)RR8\n" +
                           "QQV)PR9\n" +
                           "YGJ)D6B\n" +
                           "SFX)9VW\n" +
                           "5V4)6M8\n" +
                           "KH3)G7M\n" +
                           "B84)VWZ\n" +
                           "ZFH)H1L\n" +
                           "VMJ)MGL\n" +
                           "MYD)VCM\n" +
                           "1ZR)XDK\n" +
                           "TC1)YLL\n" +
                           "RQM)FY9\n" +
                           "L8M)F2H\n" +
                           "JM3)WHF\n" +
                           "9NV)68F\n" +
                           "FND)D9Z\n" +
                           "6LH)QPH\n" +
                           "F8N)ZTD\n" +
                           "6XX)N2Z\n" +
                           "4FH)YCF\n" +
                           "WZ9)F5R\n" +
                           "BH9)CNT\n" +
                           "5MQ)X4N\n" +
                           "62D)FTL\n" +
                           "X6R)7HW\n" +
                           "DQV)9BS\n" +
                           "H3J)R8H\n" +
                           "CNT)DQF\n" +
                           "PYM)9P1\n" +
                           "9F9)8WZ\n" +
                           "ZB5)KH3\n" +
                           "2FB)JL2\n" +
                           "PS3)BZT\n" +
                           "YKL)XPC\n" +
                           "Y7Z)DB6\n" +
                           "11D)JWS\n" +
                           "JVD)SH2\n" +
                           "775)YC8\n" +
                           "9NV)7CW\n" +
                           "Q17)MYD\n" +
                           "TH6)KBL\n" +
                           "YKS)NJC\n" +
                           "X51)5HD\n" +
                           "RZX)QM2\n" +
                           "FV2)CQY\n" +
                           "QFB)K2R\n" +
                           "K3M)3F4\n" +
                           "Q5R)7PT\n" +
                           "RH6)BGF\n" +
                           "8PP)JF8\n" +
                           "V4Q)58M\n" +
                           "X88)4HB\n" +
                           "X2R)4HK\n" +
                           "HY2)YSB\n" +
                           "HJT)G7Y\n" +
                           "76J)YM4\n" +
                           "6Q7)1YJ\n" +
                           "FCS)RDH\n" +
                           "DR3)C81\n" +
                           "4Y5)HV6\n" +
                           "TP4)S5R\n" +
                           "5NV)5VG\n" +
                           "H24)SRG\n" +
                           "XD2)63Y\n" +
                           "XYS)LPN\n" +
                           "J3P)L9Q\n" +
                           "CPF)VL3\n" +
                           "QPX)58F\n" +
                           "8ZF)T2K\n" +
                           "9BS)9CP\n" +
                           "HLC)GYM\n" +
                           "68F)24F\n" +
                           "7JQ)6VM\n" +
                           "2DN)NNQ\n" +
                           "1WV)QDC\n" +
                           "L9S)L3X\n" +
                           "XQ7)Z6X\n" +
                           "DG2)DB4\n" +
                           "3F8)QJG\n" +
                           "LKM)YB6\n" +
                           "QFR)SJX\n" +
                           "TST)YC6\n" +
                           "QQB)JGF\n" +
                           "7HW)C57\n" +
                           "9S6)JB4\n" +
                           "Z81)X5X\n" +
                           "7PD)5FX\n" +
                           "PH6)26G\n" +
                           "YCF)B9B\n" +
                           "PL5)V7Y\n" +
                           "CBN)JM3\n" +
                           "3NQ)JKJ\n" +
                           "LLC)JYN\n" +
                           "G5Q)82W\n" +
                           "F5R)44D\n" +
                           "VMD)X9S\n" +
                           "F2H)W1F\n" +
                           "2Y3)DVR\n" +
                           "NYQ)B9T\n" +
                           "DCV)FMQ\n" +
                           "8MY)V4X\n" +
                           "93G)CZ5\n" +
                           "SNV)DHX\n" +
                           "X9H)DFV\n" +
                           "QFJ)L6Y\n" +
                           "SQ6)K9Q\n" +
                           "25F)TST\n" +
                           "WW4)FQP\n" +
                           "ZWH)9MD\n" +
                           "WNM)D5G\n" +
                           "K7L)4CB\n" +
                           "56G)7LK\n" +
                           "2S4)ZVP\n" +
                           "6VM)RQ5\n" +
                           "8Z5)D28\n" +
                           "G6C)RQ4\n" +
                           "GLR)5KF\n" +
                           "Y4Y)MPF\n" +
                           "MC4)L2R\n" +
                           "JPV)L23\n" +
                           "1Y5)GPH\n" +
                           "23P)WDS\n" +
                           "99Q)DR3\n" +
                           "7RD)78B\n" +
                           "JQS)MX6\n" +
                           "VKL)3FK\n" +
                           "P51)HPL\n" +
                           "SGY)4SH\n" +
                           "QRZ)MB1\n" +
                           "P59)6TM\n" +
                           "FH7)MMT\n" +
                           "QHR)1DM\n" +
                           "H3L)XBS\n" +
                           "MGL)1WV\n" +
                           "WKF)92M\n" +
                           "R9Z)X22\n" +
                           "286)167\n" +
                           "7ZV)H9C\n" +
                           "QFR)97Z\n" +
                           "MKM)W73\n" +
                           "LZB)TLV\n" +
                           "57Q)26D\n" +
                           "47F)FLC\n" +
                           "VHF)G7V\n" +
                           "PLL)VTN\n" +
                           "NMN)2WF\n" +
                           "SWZ)DVK\n" +
                           "KBK)NGD\n" +
                           "B68)ZQQ\n" +
                           "BBZ)HV2\n" +
                           "814)52B\n" +
                           "5MG)HQW\n" +
                           "CDS)5CZ\n" +
                           "PL9)JN8\n" +
                           "3C5)GH2\n" +
                           "SBZ)RJF\n" +
                           "5KF)MZ4\n" +
                           "41G)M6C\n" +
                           "HTV)4LC\n" +
                           "H5Y)7PB\n" +
                           "MWH)XV5\n" +
                           "RR8)VKL\n" +
                           "XSR)XD7\n" +
                           "3DW)4ZV\n" +
                           "WHF)2TL\n" +
                           "4G5)P4Q\n" +
                           "VPP)LBT\n" +
                           "KWC)V9D\n" +
                           "888)GS7\n" +
                           "C5T)5V4\n" +
                           "WKQ)8Z4\n" +
                           "MKL)HJZ\n" +
                           "KBX)VPP\n" +
                           "2PT)XYS\n" +
                           "Y71)K3P\n" +
                           "RYF)KHR\n" +
                           "HPN)XJC\n" +
                           "65Y)5P4\n" +
                           "N3H)CT6\n" +
                           "B51)KGW\n" +
                           "F93)6ZG\n" +
                           "9RL)V4H\n" +
                           "M44)5Q1\n" +
                           "JMJ)T1M\n" +
                           "2TL)RQM\n" +
                           "LF7)SBQ\n" +
                           "227)ZB5\n" +
                           "XBS)HW5\n" +
                           "9NZ)YKS\n" +
                           "FFK)85M\n" +
                           "1QH)VWG\n" +
                           "4SH)9F9\n" +
                           "JWN)6C2\n" +
                           "VB8)3T2\n" +
                           "JL2)Y1J\n" +
                           "LYN)RX3\n" +
                           "DQ1)LQT\n" +
                           "NHX)YXW\n" +
                           "WS4)TGP\n" +
                           "4ZV)LVD\n" +
                           "BTP)RMR\n" +
                           "73H)VKW\n" +
                           "SB2)19H\n" +
                           "2G5)2C3\n" +
                           "K31)LL4\n" +
                           "L97)M9G\n" +
                           "K3T)CCC\n" +
                           "PJH)FDM\n" +
                           "CRV)8S2\n" +
                           "DMC)P13\n" +
                           "TGP)4RR\n" +
                           "Y7M)QZC\n" +
                           "8PP)RZH\n" +
                           "KY3)VR2\n" +
                           "646)K7L\n" +
                           "1VR)QQP\n" +
                           "GK3)RT5\n" +
                           "1DN)XZJ\n" +
                           "5FW)D9Y\n" +
                           "HNF)M9C\n" +
                           "X5T)Q41\n" +
                           "LQP)FVG\n" +
                           "MTB)DW1\n" +
                           "LFF)3J6\n" +
                           "8X5)YHV\n" +
                           "G3X)NP1\n" +
                           "Z5D)X13\n" +
                           "63G)3LZ\n" +
                           "6C8)WKF\n" +
                           "5TV)HLC\n" +
                           "RW7)ZX4\n" +
                           "J4H)9NZ\n" +
                           "KBZ)1VR\n" +
                           "4CR)MK7\n" +
                           "LZG)BV7\n" +
                           "B6Z)QKB\n" +
                           "798)VXY\n" +
                           "QM2)11D\n" +
                           "HLD)RSX\n" +
                           "6C2)YZX\n" +
                           "MTB)6LH\n" +
                           "GCH)P94\n" +
                           "3DY)SKG\n" +
                           "CV3)L97\n" +
                           "86B)YZF\n" +
                           "3X8)3KW\n" +
                           "95T)GXB\n" +
                           "44D)BD7\n" +
                           "X4N)M3P\n" +
                           "8ZW)C4C\n" +
                           "QPQ)63V\n" +
                           "S36)DGZ\n" +
                           "BCB)BTF\n" +
                           "2ZW)XTP\n" +
                           "HJQ)G6V\n" +
                           "XW3)XYT\n" +
                           "WSR)S8R\n" +
                           "79C)TKC\n" +
                           "9D6)N7L\n" +
                           "HV6)MCN\n" +
                           "58M)XR3\n" +
                           "JRL)2PT\n" +
                           "PHM)24R\n" +
                           "2S6)SBZ\n" +
                           "3F9)98N\n" +
                           "X22)MWH\n" +
                           "V9D)86B\n" +
                           "54T)CVM\n" +
                           "57R)L96\n" +
                           "G6N)N7Y\n" +
                           "6M8)6WT\n" +
                           "DLC)Q8R\n" +
                           "SN6)LRD\n" +
                           "9ZQ)FKJ\n" +
                           "T2K)GDV\n" +
                           "9TR)697\n" +
                           "YZG)RVG\n" +
                           "TZH)37N\n" +
                           "ZJY)YFF\n" +
                           "SKG)5SL\n" +
                           "WX4)WQ6\n" +
                           "ZHQ)3VF\n" +
                           "JK9)798\n" +
                           "YM3)KX9\n" +
                           "KN6)M4N\n" +
                           "G7V)SY7\n" +
                           "PG1)VNM\n" +
                           "HPL)FH7\n" +
                           "VJN)KVF\n" +
                           "28T)73H\n" +
                           "H74)CDS\n" +
                           "MG3)NMG\n" +
                           "NWN)JFF\n" +
                           "D9B)3Z2\n" +
                           "9TL)6HC\n" +
                           "2HN)9S6\n" +
                           "1MC)9TL\n" +
                           "D6T)1KM\n" +
                           "SP9)NPS\n" +
                           "HVM)D6F\n" +
                           "VF8)634\n" +
                           "NS2)SG6\n" +
                           "91S)286\n" +
                           "71T)53V\n" +
                           "H9C)SAN\n" +
                           "XXX)JL1\n" +
                           "HQW)PNV\n" +
                           "6PZ)8MY\n" +
                           "MB1)3W2\n" +
                           "WQB)YBB\n" +
                           "446)MW5\n" +
                           "HZ5)J31\n" +
                           "8PK)L8M\n" +
                           "DHX)Y5X\n" +
                           "Y4B)KBW\n" +
                           "B86)JVD\n" +
                           "BTH)HY2\n" +
                           "R6X)DQ1\n" +
                           "6GC)G9F\n" +
                           "KYR)689\n" +
                           "HV2)RZD\n" +
                           "775)WGC\n" +
                           "TRF)R11\n" +
                           "XFJ)Z4Y\n" +
                           "PXP)ZWF\n" +
                           "LNM)1FP\n" +
                           "F12)PFR\n" +
                           "4LC)5LN\n" +
                           "HMF)RML\n" +
                           "6DR)XSX\n" +
                           "RMD)NND\n" +
                           "3PY)5MF\n" +
                           "S2J)N7C\n" +
                           "LQT)TSJ\n" +
                           "697)ZYP\n" +
                           "2TH)2CT\n" +
                           "WWJ)245\n" +
                           "T5P)RL2\n" +
                           "PV7)ZWH\n" +
                           "98N)9GB\n" +
                           "SXJ)Q6P\n" +
                           "GC4)9Q9\n" +
                           "9MS)K1X\n" +
                           "73D)4XX\n" +
                           "DG2)M81\n" +
                           "QBD)DWL\n" +
                           "S8R)SVT\n" +
                           "TMD)H8S\n" +
                           "D9Z)Y96\n" +
                           "5Q1)LSB\n" +
                           "PJH)FND\n" +
                           "NKG)GTL\n" +
                           "4XY)T8V\n" +
                           "KXL)K3V\n" +
                           "PBG)TP6\n" +
                           "Z5X)5JQ\n" +
                           "JGX)87K\n" +
                           "K4V)TJM\n" +
                           "XW3)WLC\n" +
                           "HQK)YGL\n" +
                           "J5Z)K6N\n" +
                           "P1C)FBD\n" +
                           "4K1)TC1\n" +
                           "8QB)LK4\n" +
                           "Z3P)6ZZ\n" +
                           "VYV)865\n" +
                           "CT6)FK1\n" +
                           "W7J)8WX\n" +
                           "P2C)WWJ\n" +
                           "RW7)HTK\n" +
                           "82W)FJ5\n" +
                           "DDY)N5Z\n" +
                           "VWZ)YD1\n" +
                           "QQB)4TC\n" +
                           "4SH)8X2\n" +
                           "G24)JP3\n" +
                           "32D)KDZ\n" +
                           "KN1)589\n" +
                           "FH8)JCB\n" +
                           "GV6)QTH\n" +
                           "BTH)TN1\n" +
                           "HC8)LQH\n" +
                           "83C)QYM\n" +
                           "H57)H31";

    @Test
    public void testInputIsParsedIntoMap() {
        assertEquals(1604, orbits.parseToMap(input).size());
    }

    @Test
    public void testParsedInputIsClean() {
        String input = "COM)B";
        assertEquals("B", orbits.getKey(input));
        assertEquals("COM", orbits.getValue(input));
    }

    @Test
    public void testNumberOfParents() {
        assertEquals(278744, orbits.calculate(orbits.parseToMap(input)));
    }
}
